/*
 * Component Vault - OpenAPI 3.0
 *
 * \"This is a simple key-value store Some useful links: - [The sources](https://github.com/.../openapi.yaml)\"
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Secret struct {

	Key string `json:"key,omitempty"`

	Value string `json:"value,omitempty"`
}
