apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-echo
  labels:
    app: {{.Release.Name}}-{{.Values.componentname}}
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.componentname}}
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP
  selector:
    impl: {{.Release.Name}}-echo

