package org.tmform.oda.canvas.portal.component.service.console.oda;

import com.google.common.collect.ImmutableMap;
import org.apache.commons.lang3.StringUtils;

import java.util.Arrays;
import java.util.Map;
import java.util.Optional;

/**
 * 组件类型
 *
 * @author li.peilong
 * @date 2022/12/01
 * @see "https://oda-directory.labs.tmforum.org/component-map"
 */
public enum ComponentType {
    // Core Commerce Management
    productcatalogmanagement("TMFC001", "Core Commerce Management", "Product Catalog Management", "v1.0.0", "Specified", "2022-06-07", "The Product Catalog Management ODA Component implements the Product Offering and Product Specification Catalog management.", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/TMFC001"),
    purchasemanagement("", "Core Commerce Management", "Purchase Management", "v1.0.0", "Proposed", "2022-06-07", "Purchase Management deals with the purchase of products and services, and associated financial checks. It also includes the application of business policy (such as sustainability), legal and regulatory checks.", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/Purchase%20Management"),
    productinventory("TMFC005", "Core Commerce Management", "Product Inventory", "v1.0.0", "Specified", "2022-06-07", "Product Inventory component is responsible for storage and exposure of products that are assigned to and used by Parties. Product Inventory component has functionality that enables inventory items creation, inventory organization, inventory search or filter, inventory monitoring and tracking, inventory control and inventory auditing. The minimum check to be performed at inventory items creation or update is the global consistency with related Product Catalog information.", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/TMFC005"),
    productrating("", "Core Commerce Management", "Product Rating", "v1.0.0", "Proposed", "2022-06-07", "Product Rating assigns a value (monetary or other) to an event in the context of a product and payer. The rating function calculates the charges, when appropriate, across product, location, or customer, and considerations based on business rules.", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/Product%20Rating"),
    productusagemanagement("", "Core Commerce Management", "Product Usage Management", "v1.0.0", "Proposed", "2022-06-07", "Provides standardized mechanism for product usage management such as creation, update, retrieval, import and export of a collection of usages. It allows a service provider to 1) retrieve usage generated by a partner service platform in order to rate it and 2) to provide rated usage to a partner for consumption follow-up purposes", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/ProductUsageManagement"),
    productconfigurator("", "Core Commerce Management", "Product Configurator", "v1.0.0", "Specified", "2022-06-07", "The Product Configurator ODA Component is empowering sales by offering the right product combinations, controlling discounting, and automating approvals through support of configuration, pricing and quote generation activities.", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/TMFC027"),
    productordercapturevalidation("", "Core Commerce Management", "Product Order Capture & Validation", "v1.0.0", "Specified", "2022-04-04", "Addresses the means of capturing what a customer wants to order, based on the CSP Product Catalog. This component permits to choose the configuration of the product offerings and products desired, to provide a quote, to check the eligibility of the customer order, and to complete it with information needed such as the related parties, or associated the billing account and the delivery appointment if needed. This component is globally in charge of these quote management, order capture and validation steps, using dedicated components (e.g. Offering Configurator, Service Qualification, Party Mgt) when needed. After the delivery of the customer product order items, this component is also in charge of the commercial closure of the order. It includes update of the Product Inventory (status and starting/end date of tariffs and discounts) and potential commercial rules control (e.g. receipt of the contract document signed by the customer)", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/TMFC002"),
    productorderdeliveryorchestrationandmanagement("TMFC003", "Core Commerce Management", "Product Order Delivery Orchestration and Management", "v1.0.0", "Specified", "2022-04-04", "This component is in charge of the orchestration of the delivery of Product Orders (status accepted). Based on the Product specification level of information available in the Product Catalog (ex: prerequisite links between product specifications, links between product and CFS specifications, ...): it determines in which order the product specification level order items need to be delivered, and to which CFS (or Resource) specification each ordered product corresponds, and prepares and addresses each related service (or resource) order to the production system in charge. During the delivery process execution, this component is in charge of the evolution of the status of the product specification level order items, and of the related product items . So it triggers the updates of the related inventories.", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/TMFC003"),
    productassurancemanagement("", "Core Commerce Management", "Product Assurance Management", "", "Proposed", "", "Product Assurance is responsible for the management and execution of proactive and reactive rule based activities to ensure that products provided to customers are continuously available and performing according to set values for performance and quality. In cooperation with monitoring and orchestration functions Product Assurance will create an autonomic closed loop control of the performance and quality as well as mitigation of product problems and fall-outs.", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/Product%20Assurance%20Management"),
    billcalculation("", "Core Commerce Management", "Bill Calculation", "", "Future", "", "The Bill Calculation processes all charges against billing accounts during bill cycles. Bill Calculation can be executed both on a cyclic basis and on demand. It performs calculations with bill compilation of charges, credits, fees & taxes, including prorata, at various levels, such as product and/or account level that have been generated since the last run for that account, applying as well promotions and discounts.", "https://oda-directory.labs.tmforum.org/component-map/core-commerce-management/Bill%20Calculation"),

    // Party Management
    partymanagement("TMFC028", "Party Management", "Party Management", "v1.1.0", "Specified", "2022-10-11", "Party Management addresses the capture, the validation and the management in the e2e lifecycle of: Individual Organization and their description and association to: Party Role Permission Contact Medium Currency and tax exemption certificates Identification Community Profile (to be clarified if in or out) Skill (to be clarified if in or out)", "https://oda-directory.labs.tmforum.org/component-map/party-management/TMFC028"),
    salesmanagement("", "Party Management", "Sales Management", "v1.0.0", "Proposed", "2022-06-07", "Sales Management provides the necessary functionality to sell products including: reporting, commission management and reporting, forecast management, lead capture, order reporting, product support, quote management", "https://oda-directory.labs.tmforum.org/component-map/party-management/Sales%20Management"),
    brandmanagement("", "Party Management", "Brand Management", "v1.0.0", "Proposed", "2022-06-07", "Brand Management is responsible the end-to-end management of brand perception including: analysis on how a brand is perceived in the market, planning how the brand should be perceived if it is to achieve its objectives, ensuring that the brand is perceived as planned and secures its objectives. Brand management is the process of identifying the core value of a particular brand and reflecting the core value among the targeted customers", "https://oda-directory.labs.tmforum.org/component-map/party-management/Brand%20Management"),
    partyproblemmanagement("", "Party Management", "Party Problem Management", "v1.0.0", "Proposed", "2022-06-07", "The purpose of Party Problem Management is to manage problems reported by customers, suppliers, partners etc. resolving these problems to the parties' satisfaction, and providing meaningful status on the issue as needed to the party. Party problems can include: • General questions on products purchased and being used by the party • Problems with products already purchased and being used by the party either due to lack of education or service/network problems. • Problems with a material purchase from the service provider, even if they do not have an account with the said service provider. • General inquiries, complaints, and commendations", "https://oda-directory.labs.tmforum.org/component-map/party-management/Party%20Problem%20Management"),
    paymentmanagement("TMFC029", "Party Management", "Payment Management", "v1.0.0", "Planned", "2022-06-07", "Payment Management manages methods used by parties to make payments, it also administers payment plan, handles payment, assigns payments against bills, settlements, and other object requiring payments.", "https://oda-directory.labs.tmforum.org/component-map/party-management/TMFC029"),
    digitalidentitymanagement("TMFC020", "Party Management", "Digital Identity Management", "v1.0.0", "Specified", "2022-08-15", "Addresses the identity of parties via profiles. Correctly authenticates and authorizes a Party, including role management. For B2B segment this includes Customer/3rd Party identities.", "https://oda-directory.labs.tmforum.org/component-map/party-management/TMFC020"),
    billingaccountmanagement("TMFC024", "Party Management", "Billing Account Management", "v1.1.0", "Specified", "2023-04-14", "The billing account management component aims to provide all the needed functionalities to create, configure and modify billing accounts. BAM component has the goal to support and handle the following capabilities/ functionalities. Set-up/ creation of Billing account Associate payment plan(s) Associate payment method(s) – optional Account taxes/ fees exception management Define account associations Provide account balance details Set-up Billing contacts Set-up Billing preferences (e.g. bill cycle frequency, invoice media type, invoice template option, etc.)", "https://oda-directory.labs.tmforum.org/component-map/party-management/TMFC024"),
    salesdevelopment("", "Party Management", "Sales Development", "", "Proposed", "", "Sales Development provides the necessary functionality to sell products including: negotiation support, forecast analyzing, opportunity management,", "https://oda-directory.labs.tmforum.org/component-map/party-management/Sales%20Development"),
    partyinteractionmanagement("TMFC023", "Party Management", "Party Interaction Management", "v1.0.0", "Specified", "2022-12-08", "Party Interaction deals with the initial greeting and welcoming of a new contact. This will typically be the first component in a customer experience journey, shared by unassisted (self-service, retail kiosk) or assisted (call center, retail store) channels. It will identify known parties or new parties, and react appropriately to propose available actions. It records all the interactions for the parties from all channels.", "https://oda-directory.labs.tmforum.org/component-map/party-management/TMFC023"),
    partyprivacymanagement("TMFC022", "Party Management", "Party Privacy Management", "", "Future", "", "Manages the consents granted or revoked by Parties, relating to their personal information.", "https://oda-directory.labs.tmforum.org/component-map/party-management/TMFC022"),
    partytrainingandeducation("", "Party Management", "Party Training and Education", "", "Proposed", "", "Party Training and Education deals with all aspects of party training and education. This will include on-line guidance, FAQs, or complete training courses.", "https://oda-directory.labs.tmforum.org/component-map/party-management/Party%20Training%20and%20Education"),
    billinginvoicemanagement("TMFC030", "Party Management", "Billing Invoice Management", "", "Future", "", "Bill Invoice mgmt. manage the party invoice management. It addresses the invoice formatting, presentation and dispatching to the proper means of communication.", "https://oda-directory.labs.tmforum.org/component-map/party-management/TMFC030"),
    salesstrategyandplanning("", "Party Management", "Sales Strategy and Planning", "", "Proposed", "", "Sales Management provides the necessary functionality to sell products including: account planning, forecast analyzing", "https://oda-directory.labs.tmforum.org/component-map/party-management/Sales%20Strategy%20and%20Planning"),
    marketingcommunicationsandadvertising("", "Party Management", "Marketing Communications and Advertising", "", "Proposed", "", "Marketing function supports the creation of the marketing & offer strategy as part of the Lifecycle Management (LM) that includes all the marketing and offer aspects of a Product Offering. Advertising Services are primarily dealing with the enterprise's common advertising needs like Corporate advertising (that is more public relations than sales promotion) and Recruitment advertising.", "https://oda-directory.labs.tmforum.org/component-map/party-management/Marketing%20Communications%20and%20Advertising"),
    marketstrategyandpolicy("", "Party Management", "Market Strategy and Policy", "", "Proposed", "", "Market Strategy and Policy will define the market strategy and policy. It defines business and technical static policies (e.g. acceptable suppliers). And it includes the presentation of the strategy and policy.", "https://oda-directory.labs.tmforum.org/component-map/party-management/Market%20Strategy%20and%20Policy"),
    marketresearch("", "Party Management", "Market Research", "", "Proposed", "", "Market Research will be used to develop market research and the communication of the market research.", "https://oda-directory.labs.tmforum.org/component-map/party-management/Market%20Research"),
    debtcollectionmanagement("TMFC026", "Party Management", "Debt Collection Management", "", "Future", "", "Debt Collection Management component is responsible for tracking and following up with debtors, predicting and prioritizing debt recover, handling the collection of debts, handling debt litigation tasks, supporting repossessions, sending payment reminders, skip tracing and offering debt payment terms.", "https://oda-directory.labs.tmforum.org/component-map/party-management/TMFC026"),

    // Production
    serviceassurancemanagement("", "Production", "Service Assurance Management", "v1.0.0", "Proposed", "2022-06-07", "Service Assurance is responsible for the management and execution of proactive and reactive rule based activities to ensure that services provided to customers are continuously available and performing according to set values for performance and quality. In cooperation with monitoring and orchestration functions Service Assurance will create an autonomic closed loop control of the performance and quality as well as mitigation of service problems and fall-outs.", "https://oda-directory.labs.tmforum.org/component-map/production/Service%20Assurance%20Management"),
    servicebalancemanagement("TMFC013", "Production", "Service Balance Management", "v1.0.0", "Future", "2022-06-07", "Service Balance Management component is responsible for tracking usage, controlling usage, and facilitating the addition or deduction to balances related to ordered, active or delivered services. Service Balance Management component has functionality that include storing and maintaining credits, debits and reserve of balance data to support real-time and offline credit control needs. SrvBlcMgmt component supports monetary and non-monetary balances to be defined for users (or accounts) in any scenario (e.g. sole users, shared users, associated, users, hierarchical users and cross-hierarchical user relationships).", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC013"),
    servicecatalogmanagement("TMFC006", "Production", "Service Catalog Management", "v1.0.0", "Specified", "2022-06-07", "Service Catalog Management component is responsible for organizing the collection of service specifications that identify and define all requirements of a service that can be performed. Service Catalog Management component has the functionality that enable present a customer-facing view so users are able to search and select services they need, as well as a technical view to enable define and setup what's needed to deliver service specifications (Customer Facing Service Specifications (CFSSs) and Resource Facing Service Specifications (RFSSs)) contained in the service catalog. Service Catalog Management component has functionalities that include creation of new service specifications, managing service specifications, administering the lifecycle of services, describing relationships between service specification attributes, reporting on service specification and their changes, and facilitating easy and systematic indexing and access to services, as well as facilitate automating the service delivery process.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC006"),
    serviceinventory("TMFC008", "Production", "Service Inventory", "v1.0.0", "Specified", "2022-06-07", "Service Inventory component is responsible for storage and exposure of CFS (Customer Facing Service) that are associated to Product Inventory items. It is also responsible for RFS (Resource Facing Service) definition, mapping between CFS and RFS and mapping with infrastructure/network resources. Service Inventory component has functionality that enables inventory items creation, inventory organization, inventory search or filter, inventory monitoring and tracking, inventory control and inventory auditing. The minimum check to be performed at inventory items creation or update is the global consistency with related Service Catalog information", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC008"),
    serviceordermanagement("TMFC007", "Production", "Service Order Management", "v1.0.0", "Specified", "2022-06-07", "The SOM is the entry point of Production Domain. It is in charge of Customer-Facing-Service (CFS) delivery on resources (network and service platforms equipment). The SOM exposes in particular the API\" ServiceOrder\". It is triggered when the Product Order Orchestration Management component calls this API to request CFS delivery. To achieve delivery of a CFS, the SOM orchestrates the CFS delivery process which: Identifies possible RFS and chooses one, using the catalog and technical inventory. Selects the resources (servers, equipment, etc.) and their instances. Requests the ROM to update selected resource instances to deliver CFS. Request sent to the ROM contain the CFS and the list of configured resource instances to update.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC007"),
    resourcecatalogmanagement("TMFC010", "Production", "Resource Catalog Management", "v1.1.0", "Specified", "2022-10-11", "Resource Catalog Management component is responsible for organizing the collection resource specifications that identify and define all requirements for a resource. Resource Catalog Management component has the functionality that enable presenting a customer-facing view so users are able to browse and select resource they need, as well as a technical view to enable define and setup resources contained in the resource catalog. Additional functionalities include capturing specifications of new resource specifications, managing resources (registering assets and components and identifying and mapping connections/relationships), administering the lifecycle of resources, describing relationships between resources, reporting on resources and changes to their attributes, and facilitating easy access to identify and assign resources.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC010"),
    resourceordermanagement("TMFC011", "Production", "Resource Order Management", "", "Future", "", "Resource Order Management component is responsible for managing fulfillment of resource requests according to resource requirement. This component addresses all the stages of the Resource Ordering process, with functionalities that include receiving a resource order, confirming a resource order, managing the delivery of a resource order through checks for resource availability, tracking the resource order activities, correlating resource dependencies, etc., handling resource transition (updates to resource orders etc.) and resource order lifecycle state reporting etc.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC011"),
    resourceusagemanagement("TMFC016", "Production", "Resource Usage Management", "", "Future", "", "Resource Usage Management component is responsible for creating, updating, collecting / retrieving / importing, manipulating, exporting, and securing all accounts of usage of any resource. Resource Usage Management component has functionalities that include collection of usage data from all resources, converting resource usage data, transforming resource usage data, formatting resource usage data according to business needs, providing resource usage data reports, and sharing / exchanging resource usage data with specified components.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC016"),
    supplychainmanagement("", "Production", "Supply Chain Management", "", "Proposed", "", "Supply Chain Management addresses: Resource & Service Planning Resource & Service Information Management Sourcing Management Service & Resource Inventory Management Production Management Location Management Transportation Management (part of Logistics Management) Returns Management Logistic Management / Stock availability check", "https://oda-directory.labs.tmforum.org/component-map/production/Supply%20Chain%20Management"),
    resourceinventory("TMFC012", "Production", "Resource Inventory", "v1.0.0", "Specified", "2022-06-07", "Resource Inventory component is responsible for accounting for resources (all inputs - including stock, parts, assets, production components etc.) that are owned and/or held for allocation and/or use by the organization. Resource Inventory component has functionality that includes inventory items creation, inventory organization, inventory search or filter, inventory monitoring and tracking, inventory control (organization, re-stock management etc.) and inventory auditing. The minimum check to be performed at inventory items creation or update is the global consistency with related Resource Catalog information.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC012"),
    locationmanagement("TMFC014", "Production", "Location Management", "v1.0.0", "Specified", "2022-12-08", "Location Management component is responsible for organizing the collection of production-related location data in a structured information model to identify authorized use of production-related resources (e.g. HLR, VLR, HSS etc.) Location Management component facilitates holding production-related location information (such as in the domain of Mobile Networks, the International Mobile Subscriber Identity - IMSI, the phone number associated with the subscriber - MSISDN, their account status, and their last known location). Address Management component: Address Management component is responsible for planing, tracking, and managing the definition, addition, registration, assignment, and resolving of an address to a resource. An address may represent a resource (e.g IP, IMEI etc.), a location (place, site, ZIP etc.) or a mailing address (physical or virtual) as well as delivery and legal abode etc. Address Management facilitate creating, collecting, storing, standardizing, allocating, maintaining authoritative addresses correctly. Address Management must support address creation, collection and allocation in batches, ranges, streams or continuous.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC014"),
    appointmentmanagement("", "Production", "Appointment Management", "", "Proposed", "", "Appointment management provides a standardized mechanism to book an appointment with all the necessary appointment characteristics. It supports searching for free appointment slots based on parameters, as for example a party, then creating the appointment. The appointment has characteristics such as nature of appointment, place of appointment", "https://oda-directory.labs.tmforum.org/component-map/production/Appointment%20Management"),
    servicequalificationmanagement("TMFC009", "Production", "Service Qualification Management", "v1.0.0", "Specified", "2022-08-15", "Service Qualification component is responsible for checking and validating the availability of a service according to specified and configured business rules. Service Qualification component has functionality that include checking service feasibility status and publishing or reporting service qualification result.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC009"),
    serviceusagemanagement("TMFC015", "Production", "Service Usage Management", "", "Future", "", "Service Usage Management component is responsible for creating, updating, collecting / retrieving / importing, manipulating, exporting, and securing all accounts of usage of any service. Service Usage Management component has functionalities that include collection of usage data from all service points, converting service usage data, transforming service usage data, formatting service usage data according to business needs, providing service usage data reports, and sharing / exchanging service usage data with specified components.", "https://oda-directory.labs.tmforum.org/component-map/production/TMFC015"),
    // Intelligence Management
    campaignmanagement("", "Intelligence Management", "Campaign Management", "v1.0.0", "Proposed", "2022-06-07", "Campaign Management is responsible for managing the lifecycle of marketing campaigns, sometimes referred to as \"closed loop marketing\". Service Provider marketers need to respond to changing market environments with marketing initiatives that push highly targeted messages to increasingly focused segments. Marketers need an adaptable and flexible campaign management capability that can adjust to evolving customer lifecycles with corresponding targeted marketing strategies. Marketers need to deliver coordinated outbound and inbound campaigns across all points of interaction- focusing marketing resources where the greatest potential value exists. Campaign management needs to: • Leverage a single, consistent view of customer data. • Be highly usable, which increases marketing productivity and effectiveness. • Provide valuable insight into marketing performance through analytics that enable marketers to continually adjust and improve marketing investments", "https://oda-directory.labs.tmforum.org/component-map/intelligence-management/Campaign%20Management"),
    experienceinsightmanagement("", "Intelligence Management", "Experience Insight Management", "v1.0.0", "Proposed", "2022-06-07", "Experience Insight Management will be used to analyze data to provide insight into the customer and user experience. Outputs may include insights to enable the improvement of the experience, such as NPS, churn probability, etc", "https://oda-directory.labs.tmforum.org/component-map/intelligence-management/Experience%20Insight%20Management"),
    knowledgemanagement("", "Intelligence Management", "Knowledge Management", "v1.0.0", "Proposed", "2022-06-07", "Knowledge Management (KM) supports the identification, collation, labelling, storage and sharing of knowledge. Knowledge includes insights, experiences, intellectual properties (both external and internal), organizational processes and practices that are vital for the enterprise operation and development. It ensures that an organization is having access to the same set of Information and Data about the Knowledge which is acquired with the time and past experience.", "https://oda-directory.labs.tmforum.org/component-map/intelligence-management/Knowledge%20Management"),
    recommendationmanagement("", "Intelligence Management", "Recommendation Management", "v1.0.0", "Proposed", "2022-06-07", "Recommendation Management provides the functionality to drive decisions e.g.. Customer treatment and action for each specific situation based on observing what the customer is immediately experiencing. These decisions can be deterministic (i.e. business rules based), statistical (i.e. Analytical, Machine Learning (ML) or Artificial Intelligence (AI) based so treatment or recommendation is based on what has worked in the past)", "https://oda-directory.labs.tmforum.org/component-map/intelligence-management/Recommendation%20Management"),
    resourceperformancemanagement("", "Intelligence Management", "Resource Performance Management", "v1.0.0", "Proposed", "2022-06-07", "Resource Performance Management will monitor, analyze, and report on the performance of the service provider's resources.", "https://oda-directory.labs.tmforum.org/component-map/intelligence-management/Resource%20Performance%20Management"),
    serviceperformancemanagement("", "Intelligence Management", "Service Performance Management", "", "Proposed", "", "Service Performance Management will monitor, analyze, and report on the end-end service performance. This can include a real-time, end-to-end view to ensure that each service is functioning correctly as well as a historical view. These functions build on the Resource Performance data and active end-end service performance test data to provide a view of a service. The component provides a key input to determine the Quality of Service.", "https://oda-directory.labs.tmforum.org/component-map/intelligence-management/Service%20Performance%20Management"),
    // Engagement Management
    channelmanagement("", "Engagement Management", "Channel Management", "v1.0.0", "Proposed", "2022-06-07", "Channel Management encompasses the means by which customers contact Service Providers as well as how service provider agents communicate internally. Channel Management provides the means to capture and manage activities via the available contact channels (e.g. on-line contact center, web or off-line email, post, fax etc.). It also provides the means for an activity can be completed on a different channel from which the request originated.", "https://oda-directory.labs.tmforum.org/component-map/engagement-management/Channel%20Management"),
    contentmanagement("", "Engagement Management", "Content Management", "v1.0.0", "Proposed", "2022-06-07", "Content Management enables enterprise to Acquire, Document, Host and Share knowledge", "https://oda-directory.labs.tmforum.org/component-map/engagement-management/Content%20Management"),
    experiencemanagementstrategyplanning("", "Engagement Management", "Experience Management Strategy & Planning", "v1.0.0", "Proposed", "2022-06-07", "Experience Management Strategy & Planning will define the experience strategy and plan the implementation of the strategy.", "https://oda-directory.labs.tmforum.org/component-map/engagement-management/Experience%20Management%20Strategy%20&%20Planning"),
    navigationmanagement("", "Engagement Management", "Navigation Management", "v1.0.0", "Proposed", "2022-06-07", "Navigation Management provides a configurable, workflow-driven navigation – Through means such as configurable business processes, it automatically drives the agent or user journey workflow and screen navigation according to the context of the customer interaction and other customer profile information across all functions used.", "https://oda-directory.labs.tmforum.org/component-map/engagement-management/Navigation%20Management"),
    // Decoupling and Integration
    apimanagement("TMFC017", "Decoupling and Integration", "API Management", "v1.0.0", "Planned", "2022-06-07", "This API Management ODA component is responsible for managing the process of creating and publishing application programming interfaces (APIs), enabling discovery of APIs and shared resources, enforcing APIs and resource usage policies, controlling API operations, controlling access to APIs, facilitating subscription to resources, collecting and analyzing API usage statistics, reporting and visualizing based metrics, stats and performance.", "https://oda-directory.labs.tmforum.org/component-map/decoupling-and-integration/TMFC017"),
    enterpriseintegration("TMFC018", "Decoupling and Integration", "Enterprise Integration", "v1.0.0", "Future", "2022-06-07", "The Enterprise Integration component is responsible for facilitating reliable and consistent integration of components across ODA systems of records, systems of engagement and systems of insight. Functions of Enterprise Integration include ODA Component process management and automation (through the functionality of Business Process Manager), Information Routing/Message Broker (through the functionality of Enterprise Service Bus), and Component-to-Component Messaging Management (through the functionality of Messaging Oriented Middleware).", "https://oda-directory.labs.tmforum.org/component-map/decoupling-and-integration/TMFC018"),
    eventmanagement("TMFC019", "Decoupling and Integration", "Event Management", "v1.0.0", "Planned", "2022-06-07", "Event Management component is a messaging management component that is responsible for processing records of activities as they happen from components. Processing of record of activities include modelling event messages, formatting and sending/receiving messages between components (consumer/producer). Event Management component supports different patterns of usage, including Event notification (subscription), Event-sourcing (representational state changes) and Event-carried state transfer (including data needed to perform further processing). Event Management component has functionality that include message routing (asynchronous and/or synchronous), event subscription (push/pull), event storage, event connector, and event streaming in real-time to support components that serve as event producers, event processors, and event consumers. Event Management component has functionality that includes providing a centralized CQRS queryStore for all components that implement event-sourcing with event carrier state transfer. It thereby releases other components of the need to implement a query interface. The query store will implement attribute filtering, attribute selecting, iteration and sorting capabilities. The query store can support expansion of entities with references entities if the referenced entities also support event sourcing. Event Management component has functionality that include bulk operations that support exporting and importing event logs.", "https://oda-directory.labs.tmforum.org/component-map/decoupling-and-integration/TMFC019"),
    unknown("--", "unknown", "unknown", "unknown", "unknown", "unknown", "unknown", "");

    // 记录组件类型的别名
    public static final Map<String, ComponentType> ALIAS = new ImmutableMap.Builder<String, ComponentType>()
        .put("TMFC001-productcatalogmanagement", productcatalogmanagement)
        .put("TMFC005-productinventory", productinventory)
        .put("TMFC028-partymanagement", partymanagement)
        .put("TMFC029-paymentmanagement", paymentmanagement)
        .put("TMFC020-digitalidentitymanagement", digitalidentitymanagement)
        .put("TMFC024-billingaccountmanagement", billingaccountmanagement)
        .put("TMFC023-partyinteractionmanagement", partyinteractionmanagement)
        .put("TMFC022-partyprivacymanagement", partyprivacymanagement)
        .put("TMFC030-billinginvoicemanagement", billinginvoicemanagement)
        .put("TMFC026-debtcollectionmanagement", debtcollectionmanagement)
        .put("TMFC013-servicebalancemanagement", servicebalancemanagement)
        .put("TMFC006-servicecatalogmanagement", servicecatalogmanagement)
        .put("TMFC008-serviceinventory", serviceinventory)
        .put("TMFC007-serviceordermanagement", serviceordermanagement)
        .put("TMFC010-resourcecatalogmanagement", resourcecatalogmanagement)
        .put("TMFC011-resourceordermanagement", resourceordermanagement)
        .put("TMFC016-resourceusagemanagement", resourceusagemanagement)
        .put("TMFC012-resourceinventory", resourceinventory)
        .put("TMFC014-locationmanagement", locationmanagement)
        .put("TMFC009-servicequalificationmanagement", servicequalificationmanagement)
        .put("TMFC015-serviceusagemanagement", serviceusagemanagement)
        .put("TMFC017-apimanagement", apimanagement)
        .put("TMFC018-enterpriseintegration", enterpriseintegration)
        .put("TMFC019-eventmanagement", eventmanagement)
        .build();

    /**
     * 获取组件类型
     *
     * @param type
     * @return
     */
    public static ComponentType from(String type) {
        if (StringUtils.isBlank(type)) {
            return unknown;
        }

        if (ALIAS.containsKey(type)) {
            return ALIAS.get(type);
        }
        try {
            return ComponentType.valueOf(type);
        }
        catch (Exception e) {
            // 如果是这种格式xxx-组件类型，截取后面的作为类型
            String parsedType = type.substring(type.lastIndexOf("-") + 1).trim().toLowerCase();
            Optional<ComponentType> matchedType = Arrays.stream(ComponentType.values())
                .filter(odaComponentType -> StringUtils.equals(odaComponentType.name(), parsedType))
                .findAny();
            if (matchedType.isPresent()) {
                return matchedType.get();
            }
        }
        return unknown;
    }

    ComponentType(String id, String domain, String name, String version, String specStatus, String publishedDate, String description, String url) {
        setId(id);
        setDomain(domain);
        setName(name);
        setVersion(version);
        setSpecStatus(specStatus);
        setPublishedDate(publishedDate);
        setDescription(description);
        setUrl(url);
    }
    // 组件ID
    private String id;
    // 组件所属领域
    private String domain;
    // 组件名成
    private String name;
    // 组件版本
    private String version;
    // 组件规范状态
    private String specStatus;
    // 组件发布日期
    private String publishedDate;
    // 组件描述
    private String description;

    private String url;

    public String getDomain() {
        return domain;
    }

    private void setDomain(String domain) {
        this.domain = domain;
    }

    public String getName() {
        return name;
    }

    private void setName(String name) {
        this.name = name;
    }

    public String getVersion() {
        return version;
    }

    private void setVersion(String version) {
        this.version = version;
    }

    public String getSpecStatus() {
        return specStatus;
    }

    private void setSpecStatus(String specStatus) {
        this.specStatus = specStatus;
    }

    public String getPublishedDate() {
        return publishedDate;
    }

    private void setPublishedDate(String publishedDate) {
        this.publishedDate = publishedDate;
    }

    public String getDescription() {
        return description;
    }

    private void setDescription(String description) {
        this.description = description;
    }

    public String getId() {
        return id;
    }

    private void setId(String id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    private void setUrl(String url) {
        this.url = url;
    }
}
