# jaeger-values.yaml
# Simplified Jaeger configuration for ODA Canvas tracing
# Uses in-memory storage for simplicity

# Use all-in-one deployment for simplicity
allInOne:
  enabled: true
  image:
    repository: jaegertracing/all-in-one
    tag: latest
    pullPolicy: IfNotPresent
  
  # Configure storage to use memory (for testing/development)
  args:
    - --memory.max-traces=50000
    - --query.base-path=/
    - --collector.otlp.enabled=true
    - --collector.otlp.grpc.host-port=0.0.0.0:4317
    - --collector.otlp.http.host-port=0.0.0.0:4318

# Disable individual components since we're using all-in-one
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false

# Disable storage backends we don't need
storage:
  type: memory
  
# Disable Cassandra and Elasticsearch
cassandra:
  enabled: false
elasticsearch:
  enabled: false

# Configure service for external access
service:
  type: ClusterIP
  ports:
    - name: query
      port: 16686
      targetPort: 16686
    - name: collector-grpc
      port: 4317
      targetPort: 4317
    - name: collector-http
      port: 4318
      targetPort: 4318
