# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Postgres help: https://devopstales.github.io/sso/keycloak2/
# API help: https://www.appsdeveloperblog.com/keycloak-rest-api-create-a-new-user/

secret:
  # user/pass is admin/adpass, base64 encoded.
  # dbuser/dbpass: is keycloak/keycloakdbuser
  # use helm install --set to change these
  user: "admin"
  pass: "adpass"

dbaas:
  enabled: false
  vendor: "postgres"
  address: "postgres.canvas"
  port: "5432"

ingress:
  enabled: false
  class: "traefik"

service:
  port: 8088

postgresql:
  enabled: true
  auth:
    database: "keycloak"
    username: "keycloak"
    password: "keycloakdbuser"