apiVersion: v2
name: carbon-management-operator
description: A helm chart to deploy the TMFOP011 Carbon Management operator on ODA Canvas
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0
# version: 1.0.0 - initial version

# This is the version number of the application being deployed. We are versioning the canvas as the
# version of the latest component spec that it supports.
appVersion: "v1"
