#!/bin/bash

CANVASLOGS_FOLDER=$(dirname `realpath "$0"`)

PYTHON=python
if [ -f ~/.venv/canvaslogs/bin/python ]; then
   PYTHON=~/.venv/canvaslogs/bin/python
fi

FOLLOW=""
if [ "$1" = "-f" ]
then
	FOLLOW="-f"
	shift
fi

OPERATOR=$1
shift

COMP_PATTERN=""
if [[ ! "$1-" =~ ^- ]]
then 
  COMP_PATTERN="-c $1"
  shift
fi

if [ "$OPERATOR" = "comp" ]
then
    kubectl logs -n canvas deployment/component-operator -c component-operator $FOLLOW | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py $COMP_PATTERN $FOLLOW $1 $2 $3 $4 $5 $6 $7 $8 $9
elif [ "$OPERATOR" = "sman" ]
then
    kubectl logs -n canvas deployment/canvas-smanop $FOLLOW | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py $COMP_PATTERN $FOLLOW $1 $2 $3 $4 $5 $6 $7 $8 $9
elif [ "$OPERATOR" = "depapi" ]
then
    kubectl logs -n canvas deployment/canvas-depapi-op $FOLLOW | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py $COMP_PATTERN $FOLLOW $1 $2 $3 $4 $5 $6 $7 $8 $9
elif [ "$OPERATOR" = "apiistio" ]
then
    kubectl logs -n canvas deployment/api-operator-istio $FOLLOW | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py $COMP_PATTERN $FOLLOW $1 $2 $3 $4 $5 $6 $7 $8 $9
elif [ "$OPERATOR" = "idconf" ]
then
    kubectl logs -n canvas deployment/identityconfig-operator-keycloak $FOLLOW | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py $COMP_PATTERN $FOLLOW $1 $2 $3 $4 $5 $6 $7 $8 $9
elif [ "$OPERATOR" = "credman" ]
then
    kubectl logs -n canvas deployment/credentialsmanagement-operator $FOLLOW | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py $COMP_PATTERN $FOLLOW $1 $2 $3 $4 $5 $6 $7 $8 $9
else
    echo ""
    echo "usage: kubectl canvaslogs [-f] (comp|sman|depapi|apiistio|idconf|credman) [<componentfilter>] [-l <last-hours>]"
    echo "       needs python with 'pip install rich timedinput'"
    echo ""
    echo "options:"
    echo "  -f, (follow)        keep the Log Viewer open and update the display on incoming logs"
    echo "  <component-filter>  filter components by name with wildcards (*/?), e.g. \"comp-a-*\""
    echo "  -l <last-hours>     only look at the last n hours in logfile"
    echo ""
fi
