#!/bin/sh

CANVASLOGS_FOLDER=$(dirname `realpath "$0"`)
PYTHON=~/.venv/canvaslogs/bin/python

if [ "$1" = "comp" ]
then
    kubectl logs -n canvas deployment/component-operator -c component-operator | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py "$2"
elif [ "$1" = "sman" ]
then
    kubectl logs -n canvas deployment/canvas-smanop | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py "$2"
elif [ "$1" = "depapi" ]
then
    kubectl logs -n canvas deployment/canvas-smanop | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py "$2"
elif [ "$1" = "apiistio" ]
then
    kubectl logs -n canvas deployment/api-operator-istio | $PYTHON $CANVASLOGS_FOLDER/showlogtree.py "$2"
else
    echo "usage: kubectl canvaslogs (comp|sman|depapi|apiistio) [componentfilter]"
    echo "       needs python with 'pip install rich'"
fi

