name: tmf638-v5-ri

networks:
  tmf:
    external: true

services:
  ri:
    image: tmforumorg/tmf638-v5.0.0-ri:1.0.1
    platform: linux/amd64
    ports:
      - 8638:8638
      - 9638:9229
    stdin_open: true
    tty: true
    depends_on:
      - mongo
      - broker
    networks:
      tmf:
        aliases: [tmf638-ri]
    environment:
      DB_URL: mongodb://tmf638-mongo:27017
      KAFKA_BOOTSTRAP_SERVERS: tmf638-broker:9092
    command: 
      node --inspect=0.0.0.0:9229 index.js
      
  mongo:
    image: mongo:4.4.6
    networks:
      tmf:
        aliases: [tmf638-mongo]
    restart: unless-stopped
    volumes:
      - ctk_data_tmf638:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    networks:
      tmf:
        aliases: [tmf638-zookeeper]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.4.4
    networks:
      tmf:
        aliases: [tmf638-broker]
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: -1
      KAFKA_ZOOKEEPER_CONNECT: tmf638-zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://tmf638-broker:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  ctk_data_tmf638: {}
