# Stage 1: Build stage
FROM python:3.9 AS build
WORKDIR /app
# Installing necessary Python packages on .local
RUN pip install --no-cache-dir --user kopf kubernetes PyYAML requests
COPY apiOperatorApisix.py .

# Stage 2: Runtime stage
FROM python:3.9-slim
WORKDIR /app

# Copy installed packages and file from build stage
COPY --from=build /root/.local /root/.local
COPY --from=build /app/apiOperatorApisix.py .
ENV PATH=/root/.local/bin:$PATH

# Run kopf when the container launches
CMD ["kopf", "run", "apiOperatorApisix.py"]