{{- if .Values.preqrequisitechecks.istio }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install-check-istio
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccount: canvas-sm-prehook-sa
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- include "image-pull-secrets" . |nindent 6 }}
      {{- end }}
      containers:
      - name: check-istio
        image: {{ include "docker.registry" .}}{{ .Values.global.hookImages.kubectl }}
        command:
            - /bin/sh
            - -c
            - |
              # Check if the service exists in the namespace
              SERVICE=$(kubectl get svc istio-ingress -n istio-ingress --ignore-not-found)
              if [ -z "$SERVICE" ]; then
                echo "Istio is not installed properly. Service 'istio-ingress' not found in namespace 'istio-ingress'."
                exit 1
              else
                # Get the service type
                SERVICE_TYPE=$(kubectl get svc istio-ingress -n istio-ingress -o jsonpath='{.spec.type}')
                echo "Service 'istio-ingress' type: $SERVICE_TYPE"
            
                if [ "$SERVICE_TYPE" = "LoadBalancer" ]; then
                  # Check if the service has an external IP
                  EXTERNAL_IP=$(kubectl get svc istio-ingress -n istio-ingress -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
                  if [ -z "$EXTERNAL_IP" ]; then
                    EXTERNAL_IP=$(kubectl get svc istio-ingress -n istio-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
                  fi
                  if [ -z "$EXTERNAL_IP" ]; then
                    echo "Service 'istio-ingress' is of type LoadBalancer but does not have an external IP allocated."
                    exit 1
                  else
                    echo "Istio is configured properly. Service 'istio-ingress' in namespace 'istio-ingress' has an external IP: $EXTERNAL_IP."
                  fi
                elif [ "$SERVICE_TYPE" = "ClusterIP" ]; then
                  echo "Service 'istio-ingress' is of type ClusterIP. External IP is not required."

                else
                  echo "Service 'istio-ingress' is of type: $SERVICE_TYPE. Required 'LoadBalancer' and 'ClusterIP' are supported."
                  exit 1
                fi
              fi
              # Check if the VirtualService CRD exists
              VIRTUALSERVICE_CRD=$(kubectl get crd virtualservices.networking.istio.io --ignore-not-found)
              if [ -z "$VIRTUALSERVICE_CRD" ]; then
                echo "VirtualService CRD not found."
                exit 1
              else
                echo "VirtualService CRD exists. Proceeding to install the canvas."
              fi
      restartPolicy: Never
{{- end }}
