@startuml

participant Canvas as "Canvas"
entity Component
participant "Component Operator" as ComponentOperator
entity "Private Vault" as PrivateVault
participant "Private Vault Operator" as PrivateVaultOperator
participant "Kubernetes API" as KubernetesAPI
participant ComponentImplementation [
	=Component POD
	----
	Component-Implementation
]
participant PrivateVaultSideCar [
	=Component POD
	----
	Private-Vault-SideCar
]
participant CanvasVault as "Canvas Vault"


group Canvas Vault Setup 
    ...
	Canvas -> CanvasVault : setup jwt endpoint for oidc_discovery with secrets/kubernetes.io/serviceaccount/ca.crt
	...
end group

group Bootstrap - component deployment
	Component -> ComponentOperator : on.create
	ComponentOperator -> ComponentOperator : create unique Component-Instance-ID <CIID>
	ComponentOperator -> KubernetesAPI : create ServiceAccount "sa-<CIID>"
	create PrivateVault
	ComponentOperator -> PrivateVault  : extract config from Component
	PrivateVault -> PrivateVaultOperator : on.create
	PrivateVaultOperator -> CanvasVault : create Key-Value store "privatevault-<CIID>"
	PrivateVaultOperator -> CanvasVault : Setup JWT role for "sa-<CIID>" with full access to path "privatevault-<CIID>"
	group Mutate PODs which request Private-Vault-Access
		PrivateVaultOperator -> PrivateVaultSideCar : create & inject SideCar container with JWT mount, Canvas-Vault-URL and <CIID>
		ComponentImplementation <-[#ff0000]-> PrivateVaultSideCar
		activate ComponentImplementation 
		activate PrivateVaultSideCar 
	    note right of ComponentImplementation
	    started together in one POD
	    end note	
		PrivateVaultSideCar -> CanvasVault : login to "privatevault-<CIID>" using JWT of "sa-<CIID>"
    end group
	group Initialization - one-time negotiation about a token securing the localhost communication 
		ComponentImplementation -> PrivateVaultSideCar : init(seed)
		skinparam responseMessageBelowArrow true
		ComponentImplementation <-- PrivateVaultSideCar : localhost-token
    end group
end group

note over ComponentImplementation : some time later

group Runtime - component running
	ComponentImplementation -> PrivateVaultSideCar : create secret(key, value)
	PrivateVaultSideCar -> CanvasVault : create secret("privatevault-<CIID>", key, value)
	ComponentImplementation -> PrivateVaultSideCar : read secret(key)
	PrivateVaultSideCar -> CanvasVault : read secret("privatevault-<CID>", key)
	PrivateVaultSideCar  <-- CanvasVault : return secret-value
	ComponentImplementation <-- PrivateVaultSideCar : return secret-value 
end group

@enduml
