@startuml

participant Canvas as "Canvas"
entity Component
participant "Component Operator" as ComponentOperator
participant "Kubernetes API" as KubernetesAPI
participant ComponentImplementation [
	=Component POD
	----
	Component-Implementation
]
participant PrivateVaultSideCar [
	=Component POD
	----
	Private-Vault-SideCar
]
participant CanvasVault as "Canvas Vault"


group Canvas Vault Setup 
    ...
	Canvas -> CanvasVault : setup jwt endpoint for oidc_discovery with secrets/kubernetes.io/serviceaccount/ca.crt
	...
end group

group Bootstrap - component deployment
	Component -> ComponentOperator : on.create
	ComponentOperator -> ComponentOperator : create unique Component-Instance-ID <CIID>
	ComponentOperator -> KubernetesAPI : create ServiceAccount "sa-<CIID>"
	ComponentOperator -> CanvasVault : create Key-Value store "privatevault-<CIID>"
	ComponentOperator -> CanvasVault : Setup JWT role for "sa-<CIID>" with full access to path "privatevault-<CIID>"
	ComponentOperator -> PrivateVaultSideCar : create & inject SideCar container with JWT mount, Canvas-Vault-URL and <CIID>
	ComponentImplementation <-[#ff0000]-> PrivateVaultSideCar
	activate ComponentImplementation 
	activate PrivateVaultSideCar 
    note right of ComponentImplementation
    started together in one POD
    end note	
	PrivateVaultSideCar -> CanvasVault : login to "privatevault-<CIID>" using JWT of "sa-<CIID>"
	group optional - One-Time-Setup for local API access
		ComponentImplementation -> PrivateVaultSideCar : init(challenge)
		skinparam responseMessageBelowArrow true
		ComponentImplementation <-- PrivateVaultSideCar : response
    end group
end group

note over ComponentImplementation : some time later

group Runtime - component running
	ComponentImplementation -> PrivateVaultSideCar : create secret(key, value)
	PrivateVaultSideCar -> CanvasVault : create secret("privatevault-<CIID>", key, value) in 
	ComponentImplementation -> PrivateVaultSideCar : read secret(key)
	PrivateVaultSideCar -> CanvasVault : read secret("privatevault-<CID>", key)
	PrivateVaultSideCar  <-- CanvasVault : return secret-value
	ComponentImplementation <-- PrivateVaultSideCar : return secret-value 
end group

@enduml
