@startuml

actor Operations
entity Component
participant ConversionService 

participant "Other Canvas Operators"

Component <- Operations : Install
Component -> ConversionService: pre on.create
note right
    Some webhook or similar mechanism fires to convert the component before the normal on.create is issued
end note
ConversionService -> ConversionService: Convert to latest version
ConversionService -> Component: updated version
Component ->  "Other Canvas Operators": on.create

@enduml