@startuml

participant "Component\nManagement\nOperator" as ComponentOperator
entity "Observability\nResource" as Observability
participant "Observability\nManagement\nOperator" as ObservabilityOperator
participant "Observability Platform" as ObservabilityPlatform

ComponentOperator -> Observability : create/update
Observability -> ObservabilityOperator: onCreate/Update
ObservabilityOperator -> ObservabilityPlatform: Configure observability 
note right of ObservabilityPlatform
  The Observability Platform will scrape the Service Mesh and
  Cloud Platform for Technical observability data and will
  scrape the ODA Component for Business observability data
end note

@enduml