@startuml

actor Operations
entity Component
participant ConversionService 

participant "Canvas Operator 1"
participant "Canvas Operator 2"

Component <- Operations : Install
Component ->  ConversionService: on.create
note right
    Component 1 has registered for on.create events to the component resource using a prior version of the spec.
    The Conversion service intercepts the request and converts the resource to the requested version of the spec.
end note
ConversionService -> "Canvas Operator 1" : on.create
Component ->  ConversionService: on.create
note right
    Component 2has registered for on.create events to the component resource using a different version of the spec.
    The Conversion service intercepts the request and converts the resource to the requested version of the spec.
end note
ConversionService -> "Canvas Operator 2" : on.create

@enduml