@startuml

actor Operations
entity Component
participant ComponentOperator
entity PublishedNotification
participant EventPublishingEnablementOperator
participant "Event Manager" as TMFC019

Component <- Operations : Install
Component -> ComponentOperator: on.create 
group For each publishedNotification
	ComponentOperator -> PublishedNotification: create
	note right
	    A separate publishedNotification resource is created
	    for each published notification in the core function,
	    security and management sections
	end note
    PublishedNotification -> EventPublishingEnablementOperator: on.create     
    EventPublishingEnablementOperator -> TMFC019: search for matching topic
    note right
    	A topic can exist if another component
    	is already publishing these notifications
    	or if an operator pre-created topics
    end note
    alt Topic exist
    	EventPublishingEnablementOperator <-- TMFC019: Topic url
    else Topic does not exist
     	EventPublishingEnablementOperator <-- TMFC019: Not Found
    	EventPublishingEnablementOperator -> EventPublishingEnablementOperator: (optional) approval flow to approve creation of topic
    	EventPublishingEnablementOperator -> TMFC019 : configure Topic Event Hub
    	EventPublishingEnablementOperator <- TMFC019 : Topic url
    end alt
    EventPublishingEnablementOperator -> Component : configure event publishing URL
    EventPublishingEnablementOperator <-- Component
    PublishedNotification <- EventPublishingEnablementOperator: update
    ComponentOperator <- PublishedNotification: on.update
end
Component <- ComponentOperator: update 

@enduml