/*
 * Component Vault - OpenAPI 3.0
 *
 * This is a simple key-value store  Some useful links: - [The sources](https://github.com/.../openapi.yaml)
 *
 * API version: 0.1.0
 * Contact: ferenc.hechler
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

type ApiResponse struct {

	Code int32 `json:"code,omitempty"`

	Type_ string `json:"type,omitempty"`

	Message string `json:"message,omitempty"`
}
