/*
 * Component Vault - OpenAPI 3.0
 *
 * This is a simple key-value store  Some useful links: - [The sources](https://github.com/..../openapi.yaml)
 *
 * API version: 0.1.0
 * Contact: ferenc.hechler
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v3/",
		Index,
	},

	Route{
		"CreateSecret",
		strings.ToUpper("Post"),
		"/api/v3/secret",
		CreateSecret,
	},

	Route{
		"DeleteSecret",
		strings.ToUpper("Delete"),
		"/api/v3/secret/{secretkey}",
		DeleteSecret,
	},

	Route{
		"GetSecretByKey",
		strings.ToUpper("Get"),
		"/api/v3/secret/{secretkey}",
		GetSecretByKey,
	},

	Route{
		"UpdateSecret",
		strings.ToUpper("Put"),
		"/api/v3/secret/{secretkey}",
		UpdateSecret,
	},
}
