apiVersion: v1
kind: ConfigMap
metadata:
  name: component-operator-configmap
  labels:
    {{- include "component-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  LOGGING: {{ .Values.configmap.loglevel | quote }}
  COMPONENT_NAMESPACE: "{{ .Values.deployment.monitoredNamespaces }}"
  COMPONENT_NAMESPACES_CLI: {{ include "component-operator.monitoredNamespacesCLIOpts" . }}
