apiVersion: apps/v1
kind: Deployment
metadata:
  name: standard-app
  namespace: pdb-demo
  annotations:
    oda.tmforum.org/availability-class: "standard"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: standard
  template:
    metadata:
      labels:
        app: standard
    spec:
      containers:
      - name: app
        image: nginx:alpine
