apiVersion: v1
kind: ConfigMap
metadata:
  name: carbon-management-operator-configmap
  labels:
    {{- include "carbon-management-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  CARBON_INTENSITY_API_URL: "{{  .Values.env.carbonIntensityApiUrl }}"