apiVersion: v1
kind: Service
metadata:
  name: carbon-management-operator-metrics
  labels:
    {{- include "carbon-management-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: {{ .Values.service.metrics.port }}
      protocol: TCP
  selector:
    app: {{.Values.deployment.operatorName}}
