apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-patch-component-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
    #"helm.sh/hook-weight": "2"
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
      - name: patch-istio-ingress
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            kubectl patch gateways.networking.istio.io component-gateway -n components --type='json' -p='[
              {
                "op": "remove",
                "path": "/spec/servers/1"
              },
              {
                "op": "remove",
                "path": "/spec/servers/0/tls"
              }
            ]'
      restartPolicy: Never
  backoffLimit: 3