apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  KEYCLOAK_USER: {{ .Values.secret.user | b64enc | quote }}
  KEYCLOAK_PASSWORD: {{ .Values.secret.pass | b64enc | quote }}
  {{- if or .Values.dbaas.enabled .Values.postgresql.enabled }}
  DB_USER: {{ .Values.postgresql.auth.username | b64enc | }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  {{ end }}