{{ if .Values.serviceInventoryAPI.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}-svcinv-mongodb
  labels:
    app: {{.Release.Name}}-svcinv-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name}}-svcinv-mongodb
  template:
    metadata:
      labels:
        app: {{.Release.Name}}-svcinv-mongodb
    spec:
      containers:
      - name: {{.Release.Name}}-svcinv-mongodb
        image: mongo:6.0
        ports:
        - name: svcinv-mongodb
          containerPort: {{.Values.serviceInventoryAPI.mongodb.port}}
        volumeMounts:
        - name: {{.Release.Name}}-svcinv-mongodb-pv-storage
          mountPath: "/data/db"
      volumes:
      - name: {{.Release.Name}}-svcinv-mongodb-pv-storage
        persistentVolumeClaim:
          claimName: {{.Release.Name}}-svcinv-mongodb-pv-claim
{{- end }}
