apiVersion: v1
kind: Pod
metadata:
  name: custom-resource-collector
  labels:
    app: custom-resource-collector
spec:
  serviceAccountName: custom-resource-collector-sa
  containers:
  - name: collector
    image: {{ .Values.image }}:{{ .Values.imageVersion }}
    imagePullPolicy: IfNotPresent
    env:
    - name: REGISTRY_URL
      value: {{ .Values.registryUrl }}
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
  restartPolicy: Never

