apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-custom-resource-collector
  labels:
    app: {{ .Release.Name }}-custom-resource-collector
spec:
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          serviceAccountName: {{ .Release.Name }}-custom-resource-collector-sa
          containers:
          - name: collector
            image: {{ .Values.image }}:{{ .Values.imageVersion }}
            imagePullPolicy: IfNotPresent
            env:
            - name: REGISTRY_URL
              value: {{ .Values.registryUrl }}
            - name: REGISTRY_EXTERNAL_NAME
              value: {{ .Values.registryExternalName }}
            - name: MONITORED_NAMESPACES
              value: {{ .Values.monitoredNamespaces }}              
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                - ALL
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            fsGroup: 1000
          restartPolicy: Never
      backoffLimit: 0
