apiVersion: v2
name: canvas-api-gateway
description: A Helm of helm to orchestrate the ODA API Gateway installation

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
# version: 0.1.0 - baseline version of canvas-api-gateway ,can be used to deploy apisix/kong api-gateway & canvas-api-gateway operator

# This is the version number of the application being deployed. We are versioning the canvas as the
# version of the latest component spec that it supports.
appVersion: "v1beta3"

dependencies:
  - name: kong-gateway
    version: "0.1.0"
    repository: 'file://../canvas-api-gateway/kong-gateway'
    condition: kong-gateway-install.enabled
  - name: apisix-gateway
    version: "0.1.0"
    repository: 'file://../canvas-api-gateway/apisix-gateway'
    condition: apisix-gateway-install.enabled



