"""Generate a Postman collection for authenticated ODA Canvas API testing.

Creates a Postman collection with:
1. A request to obtain a JWT token via Client Credentials flow from Keycloak
2. A GET request to list resources from the API
3. A POST request to create a new resource

Usage:
  python generate_postman_collection.py \
    --keycloak-url "http://localhost:8083/auth/realms/odari" \
    --client-id <CLIENT_ID> \
    --client-secret <CLIENT_SECRET> \
    --api-base-url <API_BASE_URL> \
    --api-name "<API_NAME>" \
    --output postman_collection.json
"""
import json
import sys
import argparse


def generate_collection(keycloak_url, client_id, client_secret, api_base_url, api_name, resource_name):
    """Generate a Postman collection JSON structure."""
    # Derive a resource path from the API name if not provided
    if not resource_name:
        # Guess a common TMF resource name from the API URL
        if "productCatalog" in api_base_url:
            resource_name = "catalog"
        elif "productInventory" in api_base_url:
            resource_name = "product"
        elif "resourceInventory" in api_base_url:
            resource_name = "resource"
        elif "serviceInventory" in api_base_url:
            resource_name = "service"
        else:
            resource_name = "resource"

    collection = {
        "info": {
            "name": f"ODA Canvas - {api_name}",
            "description": f"Authenticated API testing for {api_name}.\n\nGet a JWT token from Keycloak using the Client Credentials flow, then use it to call the API through the Kong gateway.\n\nGenerated by the ODA Canvas Tutorial.",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        "variable": [
            {"key": "keycloak_url", "value": keycloak_url},
            {"key": "api_base_url", "value": api_base_url},
            {"key": "client_id", "value": client_id},
            {"key": "client_secret", "value": client_secret},
            {"key": "access_token", "value": ""}
        ],
        "item": [
            {
                "name": "1. Get JWT Token (Client Credentials)",
                "event": [
                    {
                        "listen": "test",
                        "script": {
                            "type": "text/javascript",
                            "exec": [
                                "var jsonData = pm.response.json();",
                                "pm.collectionVariables.set('access_token', jsonData.access_token);",
                                "pm.test('Token obtained successfully', function () {",
                                "    pm.response.to.have.status(200);",
                                "    pm.expect(jsonData.access_token).to.be.a('string');",
                                "});",
                                "pm.test('Token type is Bearer', function () {",
                                "    pm.expect(jsonData.token_type).to.eql('Bearer');",
                                "});",
                                "console.log('Token expires in: ' + jsonData.expires_in + 's');"
                            ]
                        }
                    }
                ],
                "request": {
                    "method": "POST",
                    "header": [
                        {"key": "Content-Type", "value": "application/x-www-form-urlencoded"}
                    ],
                    "body": {
                        "mode": "urlencoded",
                        "urlencoded": [
                            {"key": "grant_type", "value": "client_credentials"},
                            {"key": "client_id", "value": "{{client_id}}"},
                            {"key": "client_secret", "value": "{{client_secret}}"}
                        ]
                    },
                    "url": {
                        "raw": "{{keycloak_url}}/protocol/openid-connect/token",
                        "host": ["{{keycloak_url}}"],
                        "path": ["protocol", "openid-connect", "token"]
                    },
                    "description": "Obtain a JWT access token from Keycloak using the Client Credentials flow.\n\nThe test script automatically saves the token to the 'access_token' collection variable for use in subsequent requests."
                },
                "response": []
            },
            {
                "name": f"2. List {resource_name.capitalize()}s",
                "event": [
                    {
                        "listen": "test",
                        "script": {
                            "type": "text/javascript",
                            "exec": [
                                "pm.test('Status code is 200', function () {",
                                "    pm.response.to.have.status(200);",
                                "});",
                                "pm.test('Response is an array', function () {",
                                "    var jsonData = pm.response.json();",
                                "    pm.expect(jsonData).to.be.an('array');",
                                "});",
                                "var jsonData = pm.response.json();",
                                f"console.log('{resource_name.capitalize()}s returned: ' + jsonData.length);"
                            ]
                        }
                    }
                ],
                "request": {
                    "method": "GET",
                    "header": [
                        {"key": "Authorization", "value": "Bearer {{access_token}}"},
                        {"key": "Accept", "value": "application/json"}
                    ],
                    "url": {
                        "raw": f"{{{{api_base_url}}}}/{resource_name}",
                        "host": ["{{api_base_url}}"],
                        "path": [resource_name]
                    },
                    "description": f"List all {resource_name}s from the {api_name} API.\n\nRequires a valid JWT token (run 'Get JWT Token' first)."
                },
                "response": []
            },
            {
                "name": f"3. Create {resource_name.capitalize()}",
                "event": [
                    {
                        "listen": "test",
                        "script": {
                            "type": "text/javascript",
                            "exec": [
                                "pm.test('Status code is 201', function () {",
                                "    pm.response.to.have.status(201);",
                                "});",
                                "var jsonData = pm.response.json();",
                                "if (jsonData.id) {",
                                f"    pm.collectionVariables.set('{resource_name}_id', jsonData.id);",
                                "    console.log('Created ID: ' + jsonData.id);",
                                "}"
                            ]
                        }
                    }
                ],
                "request": {
                    "method": "POST",
                    "header": [
                        {"key": "Authorization", "value": "Bearer {{access_token}}"},
                        {"key": "Content-Type", "value": "application/json"},
                        {"key": "Accept", "value": "application/json"}
                    ],
                    "body": {
                        "mode": "raw",
                        "raw": json.dumps({
                            "name": f"Sample {resource_name.capitalize()}",
                            "description": f"A sample {resource_name} created via Postman",
                            "lifecycleStatus": "Active",
                            "version": "1.0"
                        }, indent=2)
                    },
                    "url": {
                        "raw": f"{{{{api_base_url}}}}/{resource_name}",
                        "host": ["{{api_base_url}}"],
                        "path": [resource_name]
                    },
                    "description": f"Create a new {resource_name} in the {api_name} API."
                },
                "response": []
            }
        ]
    }
    return collection


def main():
    parser = argparse.ArgumentParser(
        description="Generate a Postman collection for authenticated ODA Canvas API testing"
    )
    parser.add_argument("--keycloak-url", required=True,
                        help="Keycloak realm URL (e.g. http://localhost:8083/auth/realms/odari)")
    parser.add_argument("--client-id", required=True, help="Keycloak client ID")
    parser.add_argument("--client-secret", required=True, help="Keycloak client secret")
    parser.add_argument("--api-base-url", required=True,
                        help="API base URL (e.g. https://localhost/pc1-productcatalogmanagement/tmf-api/productCatalogManagement/v4)")
    parser.add_argument("--api-name", default="ODA Component API",
                        help="Display name for the API (e.g. 'Product Catalog Management TMF620')")
    parser.add_argument("--resource", default="",
                        help="Resource name for CRUD operations (e.g. 'catalog'). Auto-detected if omitted.")
    parser.add_argument("--output", default="postman_collection.json",
                        help="Output file path (default: postman_collection.json)")

    args = parser.parse_args()

    collection = generate_collection(
        args.keycloak_url,
        args.client_id,
        args.client_secret,
        args.api_base_url,
        args.api_name,
        args.resource,
    )

    with open(args.output, "w", encoding="utf-8", newline="\n") as f:
        json.dump(collection, f, indent=2, ensure_ascii=False)

    print(f"Postman collection written to: {args.output}")
    print(f"\nTo use in Postman:")
    print(f"  1. File > Import > select {args.output}")
    print(f"  2. Settings > General > disable SSL certificate verification")
    print(f"  3. Run '1. Get JWT Token' first (auto-saves token)")
    print(f"  4. Run API requests (they use the saved token)")
    print(f"  5. Token expires after 300s - re-run token request if you get 401")


if __name__ == "__main__":
    main()
