---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io]
    resources: [mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [oda.tmforum.org]
    resources: [dependentapis]
    verbs: [list, watch, get, patch]

  - apiGroups: [oda.tmforum.org]
    resources: [components]
    verbs: [list, watch, get, patch]

  - apiGroups: [oda.tmforum.org]
    resources: [exposedapis]
    verbs: [list, watch, get]

  # Application: read-only access for watching cluster-wide.
  - apiGroups: [""]
    resources: [pods]
    verbs: [list, watch, patch, delete]
    
  # Application: write access for secrets.
  - apiGroups: [""]
    resources: [secrets, configmaps]
    verbs: [list, patch, get, create, update, delete]

  # Application: read-only access for replica_Set
  - apiGroups: [apps]
    resources: [replicasets]
    verbs: [list, get]

  # Application: read-only access for deployments
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [list, get]

  # Application: create events
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
    
  # Application: create mutating webhooks 
  - apiGroups: [admissionregistration.k8s.io]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Application: full access to EnvoyFilter
  - apiGroups: [networking.istio.io]
    resources: [envoyfilters, serviceentries, destinationrules]
    verbs: [list, patch, get, create, update, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-role-cluster
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-account
    namespace: "{{ .Release.Namespace }}"
