apiVersion: apps/v1
kind: Deployment
metadata:
  name: oda-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oda-controller
  template:
    metadata:
      labels:
        app: oda-controller
    spec:
      serviceAccountName: odacomponent-account
      containers:
      - name: oda-controller
        image: tmforumodacanvas/component-istio-controller:0.2.0
        env:
        - name: LOGGING
          value: '20'           
        - name: COMPONENT_NAMESPACE
          value: 'components'           # comma separated list of namespaces
