/*
 * Private Vault - OpenAPI 3.0
 *
 * This is a simple key-value store  Some useful links: - [The sources](https://github.com/.../openapi.yaml)
 *
 * API version: 0.1.0
 * Contact: ferenc.hechler@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
	"fmt"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
)

func main() {
	init_vault()
	log.Printf("Server started")

	router := NewRouter()

	listenIP := getEnvVar("LISTEN_IP", "127.0.0.1")
	listenPort := getEnvVar("LISTEN_PORT", "5000")
	listenIPPort := fmt.Sprintf("%s:%s", listenIP, listenPort)
	fmt.Println("listening on ", listenIPPort)
	
	log.Fatal(http.ListenAndServe(listenIPPort, router))
}
