apiVersion: v1
kind: ConfigMap
metadata:
  name: api-operator-istio-configmap
  namespace: {{ .Release.Namespace }}
data:
  LOGGING: {{ .Values.configmap.loglevel | quote }}
  COMPONENT_NAMESPACE: {{.Values.deployment.monitoredNamespaces}}
  COMPONENT_NAMESPACES_CLI: {{ include "api-operator-apisix.monitoredNamespacesCLIOpts" . }}
  {{- if .Values.deployment.ingressClass.enabled }}
  INGRESS_CLASS: {{ .Values.deployment.ingressClass.name }}
  {{ end }}
  OPENMETRICS_IMPLEMENTATION: {{ .Values.deployment.openMetricsImplementation }}
  {{- if .Values.configmap.publicHostname }}
  APIOPERATORISTIO_PUBLICHOSTNAME: {{ .Values.configmap.publicHostname }}
  {{ end }}
  {{- if .Values.configmap.componentGateway }}
  APIOPERATORISTIO_COMPONENTGATEWAY: {{ .Values.configmap.componentGateway }}
  {{ end }}
