deployment:
  operatorName: dependency-management-keycloak-authz
  image: tmforumodacanvas/dependency-management-keycloak-authz
  version: 0.2.1
  prereleaseSuffix:
  imagePullPolicy: IfNotPresent
  keycloak:
    port: 8083

credentials:
  user: admin
  pass: adpass

configmap:
  # Keycloak's base url, configured according to: "http://<oda-canvas release name>-keycloak-headless.<oda-canvas release namespace>:<keycloak http port>/auth"
  kcbase: http://canvas-keycloak-headless.canvas:8083/auth
  kcrealm: odari
  loglevel: "20"
  pollIntervalSeconds: "5"
  canvasInfoEndpoint: "http://info.canvas.svc.cluster.local"

global:
  imagePullSecrets: []
