apiVersion: v1
kind: Secret
metadata:
  name: dependency-management-keycloak-authz-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dependency-management-keycloak-authz.labels" . | nindent 4 }}
data:
  KEYCLOAK_USER: {{ .Values.credentials.user | b64enc | quote }}
  KEYCLOAK_PASSWORD: {{ .Values.credentials.pass | b64enc | quote }}
