apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: pdb-demo
  annotations:
    oda.tmforum.org/availability-class: "mission-critical"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: app
        image: nginx:alpine