apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: pdb-demo
  labels:
    tier: frontend  # This matches our policy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      containers:
      - name: app
        image: nginx:alpine