@startuml

entity Component
entity "Service/Deployment/PVC"
participant componentController
entity API

Component-> componentController: Create Component
componentController -> API: Create exposedAPIs API resources
componentController -> API: Create securityAPIs API resources

"Service/Deployment/PVC"-> componentController: Create Service/Deployment/PVC
componentController-> componentController: Make child of Component
componentController-> "Service/Deployment/PVC": Update Service/Deployment/PVC

API-> componentController: API resource updated 
componentController -> Component: Update status of Component

@enduml