apiVersion: v2
name: cert-manager-init
description: A Helm chart for installing the cert manager

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.1
# version: 1.1.1 - Templatized hardcoded images
# version: 1.1.0 - updated to use v1 of CRD spec
# version: 1.0.2 - updated appVersion to v1beta4
# version: 1.0.1 - added cert for istio-ingress to enable ssl
# version: 1.0.0

# This is the version number of the application being deployed. We are versioning the canvas as the
# version of the latest component spec that it supports.
appVersion: "v1"

dependencies:
  - name: cert-manager
    version: "1.11.0"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
