---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-vault-hc-pih-sa
  namespace: {{ include "canvasvault.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-vault-hc-pih-role
  namespace: {{ include "canvasvault.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["namespaces"]
    verbs: [list]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    verbs: [create]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: [get, list, "watch"]   # "list" for kubectl wait
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods/exec"]
    verbs: [create]
  - apiGroups: [""] 
    resources: ["secrets"]
    resourceNames: ["canvas-vault-hc-secrets"]    
    verbs: [create, get, delete, patch]
  - apiGroups: ["cert-manager.io"] # "" indicates the core API group
    resources: ["certificates"]
    verbs: [create, get, patch]
  # https://github.com/kubernetes/kubectl/issues/580#issuecomment-489117173
  #- apiGroups: [""]
  #  resources: ["statefulsets", "deployments"]
  #  verbs: ["get", "list", "watch", "patch"]    
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-vault-hc-pih-rolebinding
  namespace: {{ include "canvasvault.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-vault-hc-pih-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-vault-hc-pih-sa
    namespace: {{ include "canvasvault.namespace" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "canvasvault.namespace" . }}-{{ .Release.Name }}-vault-hc-pih-clusterrole
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""] 
    resources: ["secrets"]
    #resourceNames: ["canvas-vault-hc-secrets"]    
    verbs: [create, get, delete, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "canvasvault.namespace" . }}-{{ .Release.Name }}-vault-hc-pih-clusterrolebinding
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "canvasvault.namespace" . }}-{{ .Release.Name }}-vault-hc-pih-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-vault-hc-pih-sa
    namespace: {{ include "canvasvault.namespace" . }}
