{{- if .Values.clusterRole.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canvas-portal
  #namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
    - namespaces
  verbs:
    - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - create
  - update
  - patch
- apiGroups:
    - "apps"
  resources:
    - daemonsets
    - deployments
    - deployments/rollback
    - deployments/scale
    - replicasets
    - replicasets/scale
    - statefulsets
    - statefulsets/scale
  verbs:
    - get
    - create
    - update
    - patch
    - list
    - delete
- apiGroups:
    - ""
  resources:
    - pods
    - pods/attach
    - pods/exec
    - pods/portforward
    - pods/proxy
  verbs:
    - create
    - delete
    - deletecollection
    - patch
    - update
- apiGroups:
    - ""
  resources:
    - configmaps
    - events
    - persistentvolumeclaims
    - replicationcontrollers
    - replicationcontrollers/scale
    - secrets
    - serviceaccounts
    - services
    - services/proxy
  verbs:
    - create
    - delete
    - deletecollection
    - patch
    - update
    - get
    - list
- apiGroups:
    - networking.k8s.io
  resources:
    - ingresses
    - networkpolicies
  verbs:
    - create
    - delete
    - deletecollection
    - patch
    - update
- apiGroups:
    - oda.tmforum.org
  resources:
    - components
    - apis
  verbs:
    - create
    - delete
    - patch
    - update
    - list
    - get
- apiGroups:
    - batch
  resources:
    - cronjobs
    - jobs
  verbs:
    - create
    - delete
    - patch
    - update
    - list
    - get
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - roles
    - rolebindings
  verbs:
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: canvas-portal
  #namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: canvas-portal
subjects:
  - kind: ServiceAccount
    name: canvas-portal
    namespace: {{ .Release.Namespace }}
{{- end }}