apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canvas-portal.fullname" . }}
  labels:
    {{- include "canvas-portal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "canvas-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "canvas-portal.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canvas-portal.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: canvas-portal
          env:
          - name: HELM_REPO_URL
            value: {{ .Values.env.helmRepoUrl }}
          - name: HELM_REPO_USERNAME
            value: {{ .Values.env.helmRepoUsername }}
          - name: HELM_REPO_PASSWORD
            value: {{ .Values.env.helmRepoPassword }}
          - name: PORTAL_USERNAME
            value: {{ .Values.env.portalUsername }}
          - name: PORTAL_PASSWORD
            value: {{ .Values.env.portalPassword | quote }}
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: /canvas-portal
          - name: ODA_COMPONENT_NAMESPACE
            value: '{{ join "," .Values.env.odaComponentNamespace }}'
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
