@startuml

participant ExternalClient as "External Client"
actor Operations
participant APIGateway as "API Gateway"
participant ComponentImplementation as "Component Implementation"
participant IdentityManagementSystem as "Identity Management System"

Operations -> APIGateway : Create API Key
APIGateway -> IdentityManagementSystem : Create user mapping to API Key
Operations -> ExternalClient : Provide API Key
ExternalClient -> APIGateway : Call API with API Key
APIGateway -> APIGateway: Validate API Key

group Invalid API Key
    APIGateway -> ExternalClient : Return Unauthorized (HTTP 401) response
end

APIGateway -> IdentityManagementSystem : Query user for API Key and corresponding roles
APIGateway -> APIGateway: Validate user has at least 1 role for component

group No role for component
    APIGateway -> ExternalClient : Return Unauthorized (HTTP 401) response
end

group Valid API Key and role
    APIGateway -> ComponentImplementation : Call API, including user and roles in token

    group Optionally validate token
        ComponentImplementation -> IdentityManagementSystem : Validate token
        ComponentImplementation <- IdentityManagementSystem : response
    end

    ComponentImplementation -> APIGateway: Generate response, using role for authorization (see Authorization use-case)
    APIGateway -> ExternalClient : Return response
end


@enduml