@startuml

actor Operations
entity Component
participant ComponentOperator
entity SubscribedNotifications
participant EventSubscriptionEnablementOperator
participant "Event Manager" as TMFC019

Component <- Operations : Install
Component -> ComponentOperator: on.update
group For each subscribedNotification
ComponentOperator -> SubscribedNotifications: modify
note right
    A separate subscribedNotification resource is created
    for each published notification in the core function,
    security and management sections
end note
    SubscribedNotifications -> EventSubscriptionEnablementOperator: on.modify
    EventSubscriptionEnablementOperator -> TMFC019 : reconfigure Hub
    EventSubscriptionEnablementOperator <-- TMFC019 : reconfigured
    SubscribedNotifications <- EventSubscriptionEnablementOperator: update
    ComponentOperator <- SubscribedNotifications: on.update
end
Component <- ComponentOperator: update

@enduml