@startuml

actor Operations
entity Component
participant ComponentOperator
entity ExposedAPI
participant APIExposureOperator
participant "APIGateway/Service Mesh"

Component <- Operations : Upgrade
Component -> ComponentOperator: on.update 
note right
    One or more of the APIs in the component are modified
end note
ComponentOperator -> ExposedAPI: update
note right
    For each modified API in the core function,
    security and management sections, the corresponding ExposedAPI resource is PATCHed
end note
group For each modified API
    ExposedAPI -> APIExposureOperator: on.update 
    APIExposureOperator -> "APIGateway/Service Mesh" : modify API Gateway and/or Service Mesh configuration
    "APIGateway/Service Mesh" -> "APIGateway/Service Mesh": Update status including external URL for the API
    APIExposureOperator <- "APIGateway/Service Mesh" : on.update
    ExposedAPI <- APIExposureOperator: update
    ComponentOperator <- ExposedAPI: on.update
    Component <- ComponentOperator: update 
end

@enduml