@startuml

actor Operations
entity Component
participant ComponentOperator
entity ExposedAPI
participant APIExposureOperator
participant "APIGateway/Service Mesh"

Component <- Operations : Upgrade
Component -> ComponentOperator: on.update 
note right
    One or more APIs are deleted from the component
end note
ComponentOperator -> ExposedAPI: delete
note right
    The corresponding ExposedAPI resource is deleted
    for each deleted API in the core function,
    security and management sections
end note
group For each deleted API
    ExposedAPI -> APIExposureOperator: on.delete 
    APIExposureOperator -> "APIGateway/Service Mesh" : Remove configuration in API Gateway and/or Service Mesh
    "APIGateway/Service Mesh" -> "APIGateway/Service Mesh": Success allows the ExposedAPI resource to be deleted
    ExposedAPI <- "APIGateway/Service Mesh" : allow delete
    ComponentOperator <- ExposedAPI: on.update
    Component <- ComponentOperator: update 
end

@enduml