image: tmforumodacanvas/tmf638-service-inventory-api
version: 0.1.2
prereleaseSuffix:
imagePullPolicy: IfNotPresent
serverUrl: http://info.canvas.svc.cluster.local
mongodb:
  port: 27017
  database: svcinv
  image: mongo:6.0
persistence:
  size: 1Gi
  storageClassName:
  accessModes: ReadWriteOnce
