image: tmforumodacanvas/tmf638-service-inventory-api
version: 1.0.0
prereleaseSuffix:
imagePullPolicy: IfNotPresent
serverUrl: http://info.canvas.svc.cluster.local
mongodb:
  port: 27017
  database: svcinv
  image: mongo:6.0
persistence:
  size: 1Gi
  accessModes: ReadWriteOnce
  storageClassName:
