apiVersion: oda.tmforum.org/v1
kind: Component
metadata:
  name: {{.Release.Name}}-{{.Values.componentname}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.componentname}}
spec:
  componentMetadata:
    name: {{.Values.componentname}}
    status: specified
  coreFunction:
    exposedAPIs: 
    - name: echo
      specification:
      - url: "https://doesnotexist.example.com/echotarget.json"
      implementation: {{.Release.Name}}-echo
      apiType: openapi
      path: /echo
      port: 80
    dependentAPIs: []
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  managementFunction: 
    exposedAPIs: []
  securityFunction:
    canvasSystemRole: {{.Values.canvasSystemRole}}
    exposedAPIs: []
