apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: component-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - '*.{{ .Values.domain }}'
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: false
  - hosts:
    - '*.{{ .Values.domain }}'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: domain-tls-secret
      mode: SIMPLE
