
{{ if eq (len (lookup "v1" "Namespace" "" .Values.certManagerNamespace )) 0 }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.certManagerNamespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
  labels:
    {{- include "canvas-namespaces.labels" . | nindent 4 }}
{{- end }}
