apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canvas-portal.backend.fullname" . }}
  labels:
    {{- include "canvas-portal.backend.labels" . | nindent 4 }}
type: Opaque
{{- $conformance := .Values.backend.conformance | default dict }}
{{- $canvasBDD := $conformance.canvasBDD | default dict }}
{{- $canvasBDDEnv := $canvasBDD.env | default dict }}
stringData:
  KEYCLOAK_ADMIN_CLIENT_SECRET: {{ .Values.backend.secretEnv.KEYCLOAK_ADMIN_CLIENT_SECRET | quote }}
  ENTRAID_CLIENT_SECRET: {{ .Values.backend.secretEnv.ENTRAID_CLIENT_SECRET | quote }}
  K8S_REMOTE_SA_TOKEN: {{ .Values.backend.secretEnv.K8S_REMOTE_SA_TOKEN | quote }}
  K8S_REMOTE_CA_CERT: {{ .Values.backend.secretEnv.K8S_REMOTE_CA_CERT | quote }}
  CONFORMANCE_KEYCLOAK_PASSWORD: {{ default .Values.keycloak.init.adminPassword (index $canvasBDDEnv "KEYCLOAK_PASSWORD") | quote }}
