//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityPolicy) DeepCopyInto(out *AvailabilityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityPolicy.
func (in *AvailabilityPolicy) DeepCopy() *AvailabilityPolicy {
	if in == nil {
		return nil
	}
	out := new(AvailabilityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailabilityPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityPolicyCustomDefaulter) DeepCopyInto(out *AvailabilityPolicyCustomDefaulter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityPolicyCustomDefaulter.
func (in *AvailabilityPolicyCustomDefaulter) DeepCopy() *AvailabilityPolicyCustomDefaulter {
	if in == nil {
		return nil
	}
	out := new(AvailabilityPolicyCustomDefaulter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityPolicyCustomValidator) DeepCopyInto(out *AvailabilityPolicyCustomValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityPolicyCustomValidator.
func (in *AvailabilityPolicyCustomValidator) DeepCopy() *AvailabilityPolicyCustomValidator {
	if in == nil {
		return nil
	}
	out := new(AvailabilityPolicyCustomValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityPolicyList) DeepCopyInto(out *AvailabilityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AvailabilityPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityPolicyList.
func (in *AvailabilityPolicyList) DeepCopy() *AvailabilityPolicyList {
	if in == nil {
		return nil
	}
	out := new(AvailabilityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AvailabilityPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityPolicySpec) DeepCopyInto(out *AvailabilityPolicySpec) {
	*out = *in
	in.ComponentSelector.DeepCopyInto(&out.ComponentSelector)
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]MaintenanceWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomPDBConfig != nil {
		in, out := &in.CustomPDBConfig, &out.CustomPDBConfig
		*out = new(PodDisruptionBudgetConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EnforceMinReplicas != nil {
		in, out := &in.EnforceMinReplicas, &out.EnforceMinReplicas
		*out = new(bool)
		**out = **in
	}
	if in.AllowOverride != nil {
		in, out := &in.AllowOverride, &out.AllowOverride
		*out = new(bool)
		**out = **in
	}
	if in.OverrideRequiresReason != nil {
		in, out := &in.OverrideRequiresReason, &out.OverrideRequiresReason
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityPolicySpec.
func (in *AvailabilityPolicySpec) DeepCopy() *AvailabilityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AvailabilityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AvailabilityPolicyStatus) DeepCopyInto(out *AvailabilityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AppliedToComponents != nil {
		in, out := &in.AppliedToComponents, &out.AppliedToComponents
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PDBsManaged != nil {
		in, out := &in.PDBsManaged, &out.PDBsManaged
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastAppliedTime != nil {
		in, out := &in.LastAppliedTime, &out.LastAppliedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AvailabilityPolicyStatus.
func (in *AvailabilityPolicyStatus) DeepCopy() *AvailabilityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AvailabilityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSelector) DeepCopyInto(out *ComponentSelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]v1.LabelSelectorRequirement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComponentNames != nil {
		in, out := &in.ComponentNames, &out.ComponentNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ComponentFunctions != nil {
		in, out := &in.ComponentFunctions, &out.ComponentFunctions
		*out = make([]ComponentFunction, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSelector.
func (in *ComponentSelector) DeepCopy() *ComponentSelector {
	if in == nil {
		return nil
	}
	out := new(ComponentSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceWindow) DeepCopyInto(out *MaintenanceWindow) {
	*out = *in
	if in.DaysOfWeek != nil {
		in, out := &in.DaysOfWeek, &out.DaysOfWeek
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceWindow.
func (in *MaintenanceWindow) DeepCopy() *MaintenanceWindow {
	if in == nil {
		return nil
	}
	out := new(MaintenanceWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodDisruptionBudgetConfig) DeepCopyInto(out *PodDisruptionBudgetConfig) {
	*out = *in
	if in.MinAvailable != nil {
		in, out := &in.MinAvailable, &out.MinAvailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodDisruptionBudgetConfig.
func (in *PodDisruptionBudgetConfig) DeepCopy() *PodDisruptionBudgetConfig {
	if in == nil {
		return nil
	}
	out := new(PodDisruptionBudgetConfig)
	in.DeepCopyInto(out)
	return out
}
