apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-preuninstall-patch-component-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-delete 
spec:
  template:
    spec:
      serviceAccountName: {{ .Release.Name }}-operator
      containers:
      - name: patch-istio-ingress
        image: bitnami/kubectl:latest  
        command:
          - /bin/sh
          - -c
          - |
            kubectl patch gateways.networking.istio.io component-gateway -n components --type='json' -p='[
              {
                "op": "add",
                "path": "/spec/servers/0/tls",
                "value": {
                  "httpsRedirect": true
                }
              },
              {
                "op": "add",
                "path": "/spec/servers/1",
                "value": {
                  "port": {
                    "number": 443,
                    "name": "https",
                    "protocol": "HTTPS"
                  },
                  "tls": {
                    "mode": "SIMPLE",
                    "credentialName": "istio-ingress-cert"
                  },
                  "hosts": [
                    "*"
                  ]
                }
              }
            ]'
      restartPolicy: Never
  backoffLimit: 3