apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "component-registry.fullname" . }}
  labels:
    {{- include "component-registry.labels" . | nindent 4 }}
    {{- with .Values.odaCanvas.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  gateways:
  - {{ .Values.componentGateway }}
  hosts:
  - {{ .Release.Name }}.{{ .Values.domain }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ include "component-registry.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80
