apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      serviceAccountName: serviceaccount-{{ .Release.Name }}-{{ .Values.component_iid }}
      # https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
        supplementalGroups:
        - 1001
      containers:
          
      - name: component-implementation
        image: curlimages/curl:7.88.1
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "echo waiting 2h;
           date;
           sleep 7200;
           echo --- FINISHED ---"]
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      
      - name: private-vault-sidecar
        image: mtr.devops.telekom.de/magenta_canvas/private-vault-service:0.1.0
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        env:
        - name: VAULT_ADDR
          value: "{{ .Values.vault_url }}"
        - name: VAULT_PATH
          value: "/component/{{ .Values.component_iid }}"
        - name: COMPONENT_IID
          value: "{{ .Values.component_iid }}"
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-manual
          readOnly: true
                  
      volumes:
      - name: tmp
        emptyDir: {}
      - name: kube-api-access-manual
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
              - key: ca.crt
                path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
                path: namespace      
              - fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
                path: name      
              