---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: canvas
  name: canvas-keycloak-landing-page-init-cm
data:
  init.sh: |
    #!/bin/sh
    cat <<EOF | envsubst > /usr/share/nginx/html/index.html
    <HTML>
      <HEAD><TITLE>Keycloak (Landing)</TITLE></HEAD>
      <BODY>
        <H1>Keycloak (Landing)</H1>
        <p>The admin password is:</p>
        <p> <span style="border: 1px solid black;padding:2;">$LOGIN_TOKEN</span> </p>
        <p>Continue to <a href="$LOGIN_PATH">Keycloak login</a></p>
      </BODY>
    </HTML>
    EOF
---
apiVersion: v1
kind: Service
metadata:
  namespace: canvas
  name: canvas-keycloak-landing-page
  labels:
    app: canvas-keycloak-landing-page
spec:
  selector:
    app: canvas-keycloak-landing-page
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: canvas
  name: canvas-keycloak-landing-page
  labels: 
    app: canvas-keycloak-landing-page
spec:
  selector:
    matchLabels:
      app: canvas-keycloak-landing-page
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: canvas-keycloak-landing-page
    spec:
      containers:
        - name: canvas-keycloak-landing-page
          image: nginx
          env:
          - name: LOGIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: "{{ .Values.keycloakVS.adminPwdSecretName }}"
                key: "{{ .Values.keycloakVS.adminPwdSecretKey }}"
          - name: LOGIN_PATH
            value: {{ .Values.keycloakVS.loginPath }}
          volumeMounts:
          - name: init-script
            mountPath: /docker-entrypoint.d/init
      volumes:
        - name: init-script
          configMap:
            name: canvas-keycloak-landing-page-init-cm
            defaultMode: 0777
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: canvas
  name: canvas-keycloak-landing-page-vs
  labels:
    app: canvas-keycloak-landing-page
spec:
  gateways:
  - {{ .Values.componentGateway }}
  hosts:
  - canvas-keycloak.{{ .Values.domain }}
  http:
  - match:
    - uri:
        exact: {{ .Values.keycloakVS.landigpagePrefix }}
    route:
    - destination:
        host: canvas-keycloak-landing-page.canvas.svc.cluster.local
        port:
          number: 80
