apiVersion: v2
name: canvas-vault
description: Installs and configures HashiCorp Vault as an in-cluster DEV Vault

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.2
# version: 1.0.2 - Added support for custom/private docker registry and image pull secrets
# version: 1.0.1 - Templatized hardcoded images
# version: 1.0.0 - updated to use v1 of CRD spec
# version: 0.2.1 - issue 372 - deploy non-DEV Vault with persistence and autounseal 
# version: 0.2.0 - ODAA-86: downgrade HashiCorp Vault to 1.14.8. Last version under MPLv2, 
#                  see https://www.hashicorp.com/license-faq#products-covered-by-bsl
# version: 0.1.0 - baseline version

# This is the version number of the application being deployed. We are versioning the canvas as the
# version of the latest component spec that it supports.
appVersion: "v1"

dependencies:
  - name: vault
    version: "0.26.1"
    repository: 'https://helm.releases.hashicorp.com'
