@startuml

actor Operations
entity Component
participant ComponentOperator
participant ComponentImplementation
entity DependentAPI
participant APIDiscoveryOperator



Component <- Operations : Install
Component -> ComponentOperator: on.create 
ComponentOperator -> DependentAPI: create
DependentAPI -> APIDiscoveryOperator: on.create 
APIDiscoveryOperator -> APIDiscoveryOperator : search for API matching dependency
APIDiscoveryOperator -> APIDiscoveryOperator : (optional) approval flow to approve access to API
DependentAPI <- APIDiscoveryOperator: update
ComponentOperator <- DependentAPI: on.update
Component <- ComponentOperator: update 
ComponentImplementation <- APIDiscoveryOperator: call ServiceActivationConfiguration



@enduml