apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-operator
  namespace: kong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: components
  name: {{ .Release.Name }}-operator-role-components
rules:
- apiGroups: ["oda.tmforum.org"]
  resources: ["exposedapis"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: components
  name: {{ .Release.Name }}-operator-role-istio-ingress
rules:
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["httproutes","ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["configuration.konghq.com"]
  resources: ["kongplugins"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-operator-clusterrole
rules:
- apiGroups: ["zalando.org"]
  resources: ["clusterkopfpeerings"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["oda.tmforum.org"]
  resources: ["exposedapis"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources: ["httproutes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-operator-rolebinding-components
  namespace: components
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-operator
  namespace: kong
roleRef:
  kind: Role
  name: {{ .Release.Name }}-operator-role-components
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-operator-rolebinding-istio-ingress
  namespace: kong
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-operator
  namespace: kong
roleRef:
  kind: Role
  name: {{ .Release.Name }}-operator-role-istio-ingress
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-operator
  namespace: kong
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
