apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ .Release.Name }}-http-access
  namespace: istio-ingress
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: components
  to:
    - group: ""
      kind: Service
      name: istio-ingress