#!/bin/bash

password=$(kubectl get secret --namespace grafana grafana -o jsonpath="{.data.admin-password}" | base64 -d)
echo To access the Grafana dashboard, use the following credentials:
echo
echo "    username: admin"
echo "    password: $password"
echo
