apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pdb-management-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pdb-management-operator.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "pdb-management-operator.selectorLabels" . | nindent 6 }}