{{- if and .Values.service.create .Values.deployment.enableWebhook }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pdb-management-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pdb-management-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  type: ClusterIP
{{- end }}
{{- if .Values.deployment.enableMetrics }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdb-management-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pdb-management-operator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pdb-management-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
{{- end }}