apiVersion: v2
name: secretsmanagement-operator
description: The Secrets Management Operator

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.1
# version: 1.0.1 - Templatized hardcoded images
# version: 1.0.0 - updated to use v1 of CRD spec
# version: 0.1.3 - issue 320 - SecretsManagemnt-Operator supports Canvas Log Viewer format 
# version: 0.1.2 - allow https calls to Vault with self-signed certs (VAULT_SKIP_VERIFY env var)
# version: 0.1.1 - fix linux/arm64 docker build for secretsmanagement-operator
# version: 0.1.0 - initial version

# This is the version number of the application being deployed. We are versioning the canvas as the
# version of the latest component spec that it supports.
appVersion: "v1"
