apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "subscribednotifications.oda.tmforum.org"
spec:
  group: "oda.tmforum.org"
  scope: "Namespaced"
  names:
    kind: "SubscribedNotification"
    singular: "subscribednotification"
    plural: "subscribednotifications"
  versions:
    - name: "v1beta1"
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: false
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                name:
                  type: string
                  description: Name of SubscribedNotification that this component is dependent on
                specification:
                  type: string
                  format: url
                  description: url to the specification of the Notification. e.g. url to the swagger file
                implementation:
                  type: string
                  description: The name of the service receiving the notifications
                path:
                  type: string
                  description: the path to the callback for this subscription
                port:
                  type: integer
                  description: The port where the callback is exposed 
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                uid:
                  type: string
                status:
                  type: string
                error:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: HREF
          type: string
          description: HREF
          jsonPath: .spec.href
        - name: UID
          type: string
          description: UID
          jsonPath: .status.uid
        - name: Status
          type: string
          description: Subscriber status
          jsonPath: .status.status
    - name: "v1beta2"
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: false
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                name:
                  type: string
                  description: Name of SubscribedNotification that this component is dependent on
                specification:
                  type: string
                  format: url
                  description: url to the specification of the Notification. e.g. url to the swagger file
                implementation:
                  type: string
                  description: The name of the service receiving the notifications
                path:
                  type: string
                  description: the path to the callback for this subscription
                port:
                  type: integer
                  description: The port where the callback is exposed 
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                uid:
                  type: string
                status:
                  type: string
                error:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: HREF
          type: string
          description: HREF
          jsonPath: .spec.href
        - name: UID
          type: string
          description: UID
          jsonPath: .status.uid
        - name: Status
          type: string
          description: Subscriber status
          jsonPath: .status.status
    - name: "v1beta3"
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      deprecated: false
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                name:
                  type: string
                  description: Name of the Topic that this Component is interested in listening to
                description:
                  type: string
                  description: (Optional) Description
                apitype:
                  type: string
                  enum:
                  - openapi
                  description: The type of API specification. Currently only OpenAPI (swagger) APIs are supported.
                specification:
                  type: string
                  format: url
                  description: (optional) url to the specification of the API. e.g. url to the swagger file
                implementation:
                  type: string
                  description: The name of the service receiving the notifications
                developerUI:
                  type: string
                  description: (optional) The path to the developer User Interface for the API
                callback:
                  type: string
                  description: The path to the callback endpoint
                port:
                  type: integer
                  description: The port to which the callback listens to
                query:
                  type: string
                  description: (optional) Filter the events that will be sent to callback endpoint
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                uid:
                  type: string
                status:
                  type: string
                error:
                  type: string
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Callback
          type: string
          description: Hub
          jsonPath: .spec.callback
        - name: Port
          type: string
          description: Port
          jsonPath: .spec.port
        - name: APIType
          type: string
          description: APIType
          jsonPath: .spec.apitype
        - name: UID
          type: string
          description: UID
          jsonPath: .status.uid
        - name: Status
          type: string
          description: Subscriber status
          jsonPath: .status.status
