{{ if .Values.deployment.istioGateway }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/resource-policy": keep
  name: component-gateway
  namespace: {{ .Values.deployment.monitoredNamespaces }}
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: {{ .Values.deployment.httpsRedirect }}
    hosts:
    - "{{ .Values.deployment.hostName }}"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.deployment.credentialName }}  
    hosts:
    - "{{ .Values.deployment.hostName }}"
{{ end }}