apiVersion: v1
kind: Service
metadata:
  name: seccon
  namespace: {{ .Release.Namespace }}
  labels:
    app: oda-controller #link service to Pod and not individual container
    {{- include "controller.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5000
    targetPort: seccon
    name: seccon
  type: NodePort
  selector:
    app: oda-controller
