#!/bin/sh
set -eu

APP_API_BASE_URL="${APP_API_BASE_URL:-}"
APP_KEYCLOAK_URL="${APP_KEYCLOAK_URL:-/auth}"
APP_KEYCLOAK_REALM="${APP_KEYCLOAK_REALM:-canvas}"
APP_KEYCLOAK_CLIENT_ID="${APP_KEYCLOAK_CLIENT_ID:-canvas-portal}"

cat > /usr/share/nginx/html/config.js <<EOF
window.__APP_CONFIG__ = {
  API_BASE_URL: "${APP_API_BASE_URL}",
  KEYCLOAK_URL: "${APP_KEYCLOAK_URL}",
  KEYCLOAK_REALM: "${APP_KEYCLOAK_REALM}",
  KEYCLOAK_CLIENT_ID: "${APP_KEYCLOAK_CLIENT_ID}"
};
EOF
