# Example configuration file for the ODA Component Sync Tool
# This file demonstrates all available configuration options

# Component Registry Service configuration
registry:
  url: http://localhost:8080
  external_name: component-registry
  timeout: 30
  verify_ssl: true

# Name for the registry in the Component Registry Service  
registry_name: kubernetes-cluster-registry

# Kubernetes namespaces to scan for ODA Components
namespaces:
  - components
  - prod-components
  - staging-components

# Sync behavior configuration
dry_run: false
verbose: true