apiVersion: oda.tmforum.org/v1alpha4
kind: component
metadata:
  name: {{.Release.Name}}-{{.Values.component.name}}
  labels:
    oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
spec:
  type: {{.Values.component.type}}
  selector:
    matchLabels:
     oda.tmforum.org/componentName: {{.Release.Name}}-{{.Values.component.name}}
  componentKinds:
  - group: core
    kind: Service    
  - group: core
    kind: PersistentVolumeClaim
  - group: apps
    kind: Deployment  
  version: {{.Values.component.version}}
  description: "Based on IG1228 Use Case 001 - Create a new Party" 
  maintainers:
  - name: Henrique Rodrigues
    email: hrodrigues@tmforum.org
  owners:
    - name: Henrique Rodrigues
      email: hrodrigues@tmforum.org  
  coreFunction:
    exposedAPIs: 
    - name: identitymanagement
      specification: https://raw.githubusercontent.com/tmforum-rand/Open_API_And_Data_Model/v4.0-Sprint-2020-03/apis/TMF720_Digital_Identity/swaggers/TMF720-DigitalIdentity-v4.0.0.swagger.json
      implementation: {{.Release.Name}}-digitalidentity
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/digitalIdentityManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/digitalIdentityManagement/v4/api-docs
      port: 8080 
  eventNotification:
    publishedEvents: []
    subscribedEvents: []
  management: 
    - name: metrics
      apitype: prometheus
      implementation: {{.Release.Name}}-{{.Values.component.name}}-sm
      path: /{{.Release.Name}}-{{.Values.component.name}}/metrics
      port: 4000    
  security:
    controllerRole: {{ .Values.security.controllerRole }}
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
    partyrole:
      specification: https://raw.githubusercontent.com/tmforum-apis/TMF669_PartyRole/master/TMF669-PartyRole-v4.0.0.swagger.json
      implementation: {{.Release.Name}}-partyroleapi
      apitype: openapi
      path: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4
      developerUI: /{{.Release.Name}}-{{.Values.component.name}}/tmf-api/partyRoleManagement/v4/docs
      port: 8080