
name: failure_test

on:
  workflow_dispatch:
  push:
    paths: 
      - tmp/**.*

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skiptest')"

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: check test success
      run: |
        tail -10 tmp/test_results.log
        tail -10 tmp/test_results.log | grep --color=always failed
        if tail -10 tmp/test_results.log | grep failed >/dev/null
        then 
          echo There are failed tests!
          exit 2
        else
          echo OK, no test failures.
        fi

