
name: failure_test

on:
  workflow_dispatch:
  push:
    paths: 
      - tmp/**.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Fail on errors in log
      run: |
        tail -3 tmp/test_results.json
        if tail -3 tmp/test_results.json | grep failed >/dev/null
        then 
          echo FAILED
          exit 1
        else
          echo OK
        fi

