name: Lint Python code
on: 
  pull_request:
    branches:
      - main
jobs:
  lint-python-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with: 
          src: |
            ./automation/generators/dockerbuild-workflow-generator
            ./source/operators/TMFOP001-Component-Management/component-management
            ./source/operators/TMFOP002-API-Management/istio
            ./source/operators/TMFOP005-Dependency-Management/simple-dependency-management
            ./source/operators/TMFOP007-Secrets-Management/vault
