kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Release.Name}}-svcinv-mongodb-pv-claim
  labels:
    app: {{ .Release.Name }}-svcinv-mongodb
spec:
  {{ if .Values.persistence.storageClassName -}}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
  - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
