apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-svcinv-mongodb
  labels:
    app: {{.Release.Name}}-svcinv-mongodb
spec:
  ports:
  - port: {{.Values.mongodb.port}}
    targetPort: svcinv-mongodb
    name: tcp-svcinv-mongodb
  selector:
    app: {{.Release.Name}}-svcinv-mongodb
