export default {
    ODA: {
        CREATE_INSTANCE: 'Create Instance',
        ODA_STATUS: 'ODA Status',
        ODA_MAP: 'ODA Map',
        COMPONENT_INSTANCES: 'Component Instances',
        COMPLIANCE_TEST: 'Compliance Test',
        ORCHESTRATION: 'Orchestration',
        CONFIRM: 'Confirm',
        CANCEL: 'Cancel',
        INSTANCE_SEARCH_TIP: 'Please enter instance name, type, Domain, vendor',
        INSTANCE_NAME: 'Instance Name',
        TYPE: 'Type',
        VENDOR: 'Vendor',
        STATUS: 'Status',
        VERSION: 'Version',
        DESCRIPTION: 'Description',
        CREATE_TIME: 'Create Time',
        OPERATION: 'Operation',
        DETAIL: 'Details',
        UPGRADE: 'Upgrade',
        DELETE: 'Delete',
        OK: 'Ok',
        CANNOT_EMPTY: 'This field is required',
        LOWER_NUMBER: 'Lowercase letters, numbers, hyphens',
        NEW_INSTANCE: 'New Instance',
        UPGRADE_INSTANCE: 'upgrade Instance',
        BASIC_INFORMATION: 'Basic Info',
        NAME: 'Name',
        ODA_COMPONENT: 'ODA component',
        SELECT_COMPONENT: 'Select Component Chart',
        SELECT_VERSION: 'Select Version',
        INSTANCE_CONFIGURATION: 'Instance Configuration',
        CONFIRM_LOGOUT: 'Are you sure to logout?',
        LOGOUT_SUCCESS: 'Logout success',
        LOGOUT: 'Logout',
        VIEW_YAML: 'View Yaml',
        NAMESPACE: 'Namespace',
        CHART_VERSION: 'Chart version',
        EVENT: 'Event',
        RESOURCE: 'Resource',
        HISTORY_REVISION: 'History Revision',
        API_DOC: 'API doc',
        RESOURCE_NAME: 'Resource Name',
        SWITCH_LAN: 'Chinese',
        CREATE: 'New',
        RULES: 'Rules',
        UNINSTALL_INSTANCE_CONFIRM: 'Confirm to delete the component instance '
    }
};